/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.sources;

import com.newscatcher.api.core.ClientOptions;
import com.newscatcher.api.core.RequestOptions;
import com.newscatcher.api.resources.sources.requests.SourcesGetRequest;
import com.newscatcher.api.resources.sources.requests.SourcesPostRequest;
import com.newscatcher.api.types.SourcesResponseDto;

public class SourcesClient {
    protected final ClientOptions clientOptions;

    private final RawSourcesClient rawClient;

    public SourcesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSourcesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSourcesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieves a list of sources based on specified criteria such as language, country, rank, and more.
     */
    public SourcesResponseDto get() {
        return this.rawClient.get().body();
    }

    /**
     * Retrieves a list of sources based on specified criteria such as language, country, rank, and more.
     */
    public SourcesResponseDto get(SourcesGetRequest request) {
        return this.rawClient.get(request).body();
    }

    /**
     * Retrieves a list of sources based on specified criteria such as language, country, rank, and more.
     */
    public SourcesResponseDto get(SourcesGetRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).body();
    }

    /**
     * Retrieves the list of sources available in the database. You can filter the sources by language, country, and more.
     */
    public SourcesResponseDto post() {
        return this.rawClient.post().body();
    }

    /**
     * Retrieves the list of sources available in the database. You can filter the sources by language, country, and more.
     */
    public SourcesResponseDto post(SourcesPostRequest request) {
        return this.rawClient.post(request).body();
    }

    /**
     * Retrieves the list of sources available in the database. You can filter the sources by language, country, and more.
     */
    public SourcesResponseDto post(SourcesPostRequest request, RequestOptions requestOptions) {
        return this.rawClient.post(request, requestOptions).body();
    }
}
