/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.authors.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.api.core.ObjectMappers;
import com.newscatcher.api.types.From;
import com.newscatcher.api.types.SortBy;
import com.newscatcher.api.types.To;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetAuthorsRequest.Builder.class)
public final class GetAuthorsRequest {
    private final String authorName;

    private final Optional<String> notAuthorName;

    private final Optional<String> predefinedSources;

    private final Optional<String> sources;

    private final Optional<String> notSources;

    private final Optional<String> lang;

    private final Optional<String> notLang;

    private final Optional<String> countries;

    private final Optional<String> notCountries;

    private final Optional<From> from;

    private final Optional<To> to;

    private final Optional<String> publishedDatePrecision;

    private final Optional<Boolean> byParseDate;

    private final Optional<SortBy> sortBy;

    private final Optional<Boolean> rankedOnly;

    private final Optional<Integer> fromRank;

    private final Optional<Integer> toRank;

    private final Optional<Boolean> isHeadline;

    private final Optional<Boolean> isOpinion;

    private final Optional<Boolean> isPaidContent;

    private final Optional<String> parentUrl;

    private final Optional<String> allLinks;

    private final Optional<String> allDomainLinks;

    private final Optional<String> allLinksText;

    private final Optional<Integer> wordCountMin;

    private final Optional<Integer> wordCountMax;

    private final Optional<Integer> page;

    private final Optional<Integer> pageSize;

    private final Optional<Boolean> includeTranslationFields;

    private final Optional<Boolean> includeNlpData;

    private final Optional<Boolean> hasNlp;

    private final Optional<String> theme;

    private final Optional<String> notTheme;

    private final Optional<String> nerName;

    private final Optional<Float> titleSentimentMin;

    private final Optional<Float> titleSentimentMax;

    private final Optional<Float> contentSentimentMin;

    private final Optional<Float> contentSentimentMax;

    private final Optional<String> iptcTags;

    private final Optional<String> notIptcTags;

    private final Optional<String> iabTags;

    private final Optional<String> notIabTags;

    private final Optional<String> customTags;

    private final Optional<Boolean> robotsCompliant;

    private final Map<String, Object> additionalProperties;

    private GetAuthorsRequest(
            String authorName,
            Optional<String> notAuthorName,
            Optional<String> predefinedSources,
            Optional<String> sources,
            Optional<String> notSources,
            Optional<String> lang,
            Optional<String> notLang,
            Optional<String> countries,
            Optional<String> notCountries,
            Optional<From> from,
            Optional<To> to,
            Optional<String> publishedDatePrecision,
            Optional<Boolean> byParseDate,
            Optional<SortBy> sortBy,
            Optional<Boolean> rankedOnly,
            Optional<Integer> fromRank,
            Optional<Integer> toRank,
            Optional<Boolean> isHeadline,
            Optional<Boolean> isOpinion,
            Optional<Boolean> isPaidContent,
            Optional<String> parentUrl,
            Optional<String> allLinks,
            Optional<String> allDomainLinks,
            Optional<String> allLinksText,
            Optional<Integer> wordCountMin,
            Optional<Integer> wordCountMax,
            Optional<Integer> page,
            Optional<Integer> pageSize,
            Optional<Boolean> includeTranslationFields,
            Optional<Boolean> includeNlpData,
            Optional<Boolean> hasNlp,
            Optional<String> theme,
            Optional<String> notTheme,
            Optional<String> nerName,
            Optional<Float> titleSentimentMin,
            Optional<Float> titleSentimentMax,
            Optional<Float> contentSentimentMin,
            Optional<Float> contentSentimentMax,
            Optional<String> iptcTags,
            Optional<String> notIptcTags,
            Optional<String> iabTags,
            Optional<String> notIabTags,
            Optional<String> customTags,
            Optional<Boolean> robotsCompliant,
            Map<String, Object> additionalProperties) {
        this.authorName = authorName;
        this.notAuthorName = notAuthorName;
        this.predefinedSources = predefinedSources;
        this.sources = sources;
        this.notSources = notSources;
        this.lang = lang;
        this.notLang = notLang;
        this.countries = countries;
        this.notCountries = notCountries;
        this.from = from;
        this.to = to;
        this.publishedDatePrecision = publishedDatePrecision;
        this.byParseDate = byParseDate;
        this.sortBy = sortBy;
        this.rankedOnly = rankedOnly;
        this.fromRank = fromRank;
        this.toRank = toRank;
        this.isHeadline = isHeadline;
        this.isOpinion = isOpinion;
        this.isPaidContent = isPaidContent;
        this.parentUrl = parentUrl;
        this.allLinks = allLinks;
        this.allDomainLinks = allDomainLinks;
        this.allLinksText = allLinksText;
        this.wordCountMin = wordCountMin;
        this.wordCountMax = wordCountMax;
        this.page = page;
        this.pageSize = pageSize;
        this.includeTranslationFields = includeTranslationFields;
        this.includeNlpData = includeNlpData;
        this.hasNlp = hasNlp;
        this.theme = theme;
        this.notTheme = notTheme;
        this.nerName = nerName;
        this.titleSentimentMin = titleSentimentMin;
        this.titleSentimentMax = titleSentimentMax;
        this.contentSentimentMin = contentSentimentMin;
        this.contentSentimentMax = contentSentimentMax;
        this.iptcTags = iptcTags;
        this.notIptcTags = notIptcTags;
        this.iabTags = iabTags;
        this.notIabTags = notIabTags;
        this.customTags = customTags;
        this.robotsCompliant = robotsCompliant;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("author_name")
    public String getAuthorName() {
        return authorName;
    }

    /**
     * @return The list of author names to exclude from your search. To exclude articles by specific authors, use a comma-separated string.
     */
    @JsonProperty("not_author_name")
    public Optional<String> getNotAuthorName() {
        return notAuthorName;
    }

    /**
     * @return Predefined top news sources per country.
     * <p>Format: start with the word <code>top</code>, followed by the number of desired sources, and then the two-letter country code <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a>.</p>
     * <p>Multiple countries with the number of top sources can be specified as a comma-separated string.</p>
     */
    @JsonProperty("predefined_sources")
    public Optional<String> getPredefinedSources() {
        return predefinedSources;
    }

    /**
     * @return One or more news sources to narrow down the search. The format must be a domain URL. Subdomains, such as <code>finance.yahoo.com</code>, are also acceptable.To specify multiple sources, use a comma-separated string.
     */
    @JsonProperty("sources")
    public Optional<String> getSources() {
        return sources;
    }

    /**
     * @return The news sources to exclude from the search. To exclude multiple sources, use a comma-separated string.
     */
    @JsonProperty("not_sources")
    public Optional<String> getNotSources() {
        return notSources;
    }

    /**
     * @return The language(s) of the search. The only accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_639-1">ISO 639-1</a> code. To select multiple languages, use a comma-separated string.
     * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang">Enumerated parameters &gt; Language</a>.</p>
     */
    @JsonProperty("lang")
    public Optional<String> getLang() {
        return lang;
    }

    /**
     * @return The language(s) to exclude from the search. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_639-1">ISO 639-1</a> code. To exclude multiple languages, use a comma-separated string.
     * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang">Enumerated parameters &gt; Language</a>.</p>
     */
    @JsonProperty("not_lang")
    public Optional<String> getNotLang() {
        return notLang;
    }

    /**
     * @return The countries where the news publisher is located. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a> code. To select multiple countries, use a comma-separated string.
     * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country">Enumerated parameters &gt; Country</a>.</p>
     */
    @JsonProperty("countries")
    public Optional<String> getCountries() {
        return countries;
    }

    /**
     * @return The publisher location countries to exclude from the search. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a> code. To exclude multiple countries, use a comma-separated string.
     * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country">Enumerated parameters &gt; Country</a>.</p>
     */
    @JsonProperty("not_countries")
    public Optional<String> getNotCountries() {
        return notCountries;
    }

    @JsonProperty("from_")
    public Optional<From> getFrom() {
        return from;
    }

    @JsonProperty("to_")
    public Optional<To> getTo() {
        return to;
    }

    @JsonProperty("published_date_precision")
    public Optional<String> getPublishedDatePrecision() {
        return publishedDatePrecision;
    }

    @JsonProperty("by_parse_date")
    public Optional<Boolean> getByParseDate() {
        return byParseDate;
    }

    @JsonProperty("sort_by")
    public Optional<SortBy> getSortBy() {
        return sortBy;
    }

    @JsonProperty("ranked_only")
    public Optional<Boolean> getRankedOnly() {
        return rankedOnly;
    }

    @JsonProperty("from_rank")
    public Optional<Integer> getFromRank() {
        return fromRank;
    }

    @JsonProperty("to_rank")
    public Optional<Integer> getToRank() {
        return toRank;
    }

    @JsonProperty("is_headline")
    public Optional<Boolean> getIsHeadline() {
        return isHeadline;
    }

    @JsonProperty("is_opinion")
    public Optional<Boolean> getIsOpinion() {
        return isOpinion;
    }

    @JsonProperty("is_paid_content")
    public Optional<Boolean> getIsPaidContent() {
        return isPaidContent;
    }

    /**
     * @return The categorical URL(s) to filter your search. To filter your search by multiple categorical URLs, use a comma-separated string.
     */
    @JsonProperty("parent_url")
    public Optional<String> getParentUrl() {
        return parentUrl;
    }

    /**
     * @return The complete URL(s) mentioned in the article. For multiple URLs, use a comma-separated string.
     * <p>For more details, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
     */
    @JsonProperty("all_links")
    public Optional<String> getAllLinks() {
        return allLinks;
    }

    /**
     * @return The domain(s) mentioned in the article. For multiple domains, use a comma-separated string.
     * <p>For more details, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
     */
    @JsonProperty("all_domain_links")
    public Optional<String> getAllDomainLinks() {
        return allDomainLinks;
    }

    /**
     * @return The text content of links mentioned in the article. Searches for links where the anchor text contains the specified terms. For multiple terms, use a comma-separated string.
     * <p><strong>Note</strong>: When this parameter is used, the response includes the <code>all_links_data</code> field with detailed link information.</p>
     * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
     */
    @JsonProperty("all_links_text")
    public Optional<String> getAllLinksText() {
        return allLinksText;
    }

    @JsonProperty("word_count_min")
    public Optional<Integer> getWordCountMin() {
        return wordCountMin;
    }

    @JsonProperty("word_count_max")
    public Optional<Integer> getWordCountMax() {
        return wordCountMax;
    }

    @JsonProperty("page")
    public Optional<Integer> getPage() {
        return page;
    }

    @JsonProperty("page_size")
    public Optional<Integer> getPageSize() {
        return pageSize;
    }

    @JsonProperty("include_translation_fields")
    public Optional<Boolean> getIncludeTranslationFields() {
        return includeTranslationFields;
    }

    @JsonProperty("include_nlp_data")
    public Optional<Boolean> getIncludeNlpData() {
        return includeNlpData;
    }

    @JsonProperty("has_nlp")
    public Optional<Boolean> getHasNlp() {
        return hasNlp;
    }

    @JsonProperty("theme")
    public Optional<String> getTheme() {
        return theme;
    }

    @JsonProperty("not_theme")
    public Optional<String> getNotTheme() {
        return notTheme;
    }

    @JsonProperty("ner_name")
    public Optional<String> getNerName() {
        return nerName;
    }

    @JsonProperty("title_sentiment_min")
    public Optional<Float> getTitleSentimentMin() {
        return titleSentimentMin;
    }

    @JsonProperty("title_sentiment_max")
    public Optional<Float> getTitleSentimentMax() {
        return titleSentimentMax;
    }

    @JsonProperty("content_sentiment_min")
    public Optional<Float> getContentSentimentMin() {
        return contentSentimentMin;
    }

    @JsonProperty("content_sentiment_max")
    public Optional<Float> getContentSentimentMax() {
        return contentSentimentMax;
    }

    /**
     * @return Filters articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags, use a comma-separated string of tag IDs.
     * <p><strong>Note</strong>: The <code>iptc_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
     * <p>To learn more, see <a href="https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html">IPTC Media Topic NewsCodes</a>.</p>
     */
    @JsonProperty("iptc_tags")
    public Optional<String> getIptcTags() {
        return iptcTags;
    }

    /**
     * @return Inverse of the <code>iptc_tags</code> parameter. Excludes articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags to exclude, use a comma-separated string of tag IDs.
     * <p><strong>Note</strong>: The <code>not_iptc_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
     * <p>To learn more, see <a href="https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html">IPTC Media Topic NewsCodes</a>.</p>
     */
    @JsonProperty("not_iptc_tags")
    public Optional<String> getNotIptcTags() {
        return notIptcTags;
    }

    /**
     * @return Filters articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories, use a comma-separated string.
     * <p><strong>Note</strong>: The <code>iab_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
     * <p>To learn more, see the <a href="https://iabtechlab.com/standards/content-taxonomy/">IAB Content taxonomy</a>.</p>
     */
    @JsonProperty("iab_tags")
    public Optional<String> getIabTags() {
        return iabTags;
    }

    /**
     * @return Inverse of the <code>iab_tags</code> parameter. Excludes articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories to exclude, use a comma-separated string.
     * <p><strong>Note</strong>: The <code>not_iab_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
     * <p>To learn more, see the <a href="https://iabtechlab.com/standards/content-taxonomy/">IAB Content taxonomy</a>.</p>
     */
    @JsonProperty("not_iab_tags")
    public Optional<String> getNotIabTags() {
        return notIabTags;
    }

    /**
     * @return Filters articles based on provided taxonomy that is tailored to your specific needs and is accessible only with your API key. To specify tags, use the following pattern:
     * <ul>
     * <li><code>custom_tags.taxonomy=Tag1,Tag2</code>, where <code>taxonomy</code> is the taxonomy name and <code>Tag1,Tag2</code> is a comma-separated list of tag names.</li>
     * </ul>
     * <p>Example: <code>custom_tags.industry=&quot;Manufacturing,Logistics&quot;</code></p>
     * <p>To learn more, see the <a href="https://www.newscatcherapi.com/docs/news-api/guides-and-concepts/custom-tags">Custom tags</a>.</p>
     */
    @JsonProperty("custom_tags")
    public Optional<String> getCustomTags() {
        return customTags;
    }

    @JsonProperty("robots_compliant")
    public Optional<Boolean> getRobotsCompliant() {
        return robotsCompliant;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetAuthorsRequest && equalTo((GetAuthorsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetAuthorsRequest other) {
        return authorName.equals(other.authorName)
                && notAuthorName.equals(other.notAuthorName)
                && predefinedSources.equals(other.predefinedSources)
                && sources.equals(other.sources)
                && notSources.equals(other.notSources)
                && lang.equals(other.lang)
                && notLang.equals(other.notLang)
                && countries.equals(other.countries)
                && notCountries.equals(other.notCountries)
                && from.equals(other.from)
                && to.equals(other.to)
                && publishedDatePrecision.equals(other.publishedDatePrecision)
                && byParseDate.equals(other.byParseDate)
                && sortBy.equals(other.sortBy)
                && rankedOnly.equals(other.rankedOnly)
                && fromRank.equals(other.fromRank)
                && toRank.equals(other.toRank)
                && isHeadline.equals(other.isHeadline)
                && isOpinion.equals(other.isOpinion)
                && isPaidContent.equals(other.isPaidContent)
                && parentUrl.equals(other.parentUrl)
                && allLinks.equals(other.allLinks)
                && allDomainLinks.equals(other.allDomainLinks)
                && allLinksText.equals(other.allLinksText)
                && wordCountMin.equals(other.wordCountMin)
                && wordCountMax.equals(other.wordCountMax)
                && page.equals(other.page)
                && pageSize.equals(other.pageSize)
                && includeTranslationFields.equals(other.includeTranslationFields)
                && includeNlpData.equals(other.includeNlpData)
                && hasNlp.equals(other.hasNlp)
                && theme.equals(other.theme)
                && notTheme.equals(other.notTheme)
                && nerName.equals(other.nerName)
                && titleSentimentMin.equals(other.titleSentimentMin)
                && titleSentimentMax.equals(other.titleSentimentMax)
                && contentSentimentMin.equals(other.contentSentimentMin)
                && contentSentimentMax.equals(other.contentSentimentMax)
                && iptcTags.equals(other.iptcTags)
                && notIptcTags.equals(other.notIptcTags)
                && iabTags.equals(other.iabTags)
                && notIabTags.equals(other.notIabTags)
                && customTags.equals(other.customTags)
                && robotsCompliant.equals(other.robotsCompliant);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.authorName,
                this.notAuthorName,
                this.predefinedSources,
                this.sources,
                this.notSources,
                this.lang,
                this.notLang,
                this.countries,
                this.notCountries,
                this.from,
                this.to,
                this.publishedDatePrecision,
                this.byParseDate,
                this.sortBy,
                this.rankedOnly,
                this.fromRank,
                this.toRank,
                this.isHeadline,
                this.isOpinion,
                this.isPaidContent,
                this.parentUrl,
                this.allLinks,
                this.allDomainLinks,
                this.allLinksText,
                this.wordCountMin,
                this.wordCountMax,
                this.page,
                this.pageSize,
                this.includeTranslationFields,
                this.includeNlpData,
                this.hasNlp,
                this.theme,
                this.notTheme,
                this.nerName,
                this.titleSentimentMin,
                this.titleSentimentMax,
                this.contentSentimentMin,
                this.contentSentimentMax,
                this.iptcTags,
                this.notIptcTags,
                this.iabTags,
                this.notIabTags,
                this.customTags,
                this.robotsCompliant);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AuthorNameStage builder() {
        return new Builder();
    }

    public interface AuthorNameStage {
        _FinalStage authorName(@NotNull String authorName);

        Builder from(GetAuthorsRequest other);
    }

    public interface _FinalStage {
        GetAuthorsRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The list of author names to exclude from your search. To exclude articles by specific authors, use a comma-separated string.</p>
         */
        _FinalStage notAuthorName(Optional<String> notAuthorName);

        _FinalStage notAuthorName(String notAuthorName);

        /**
         * <p>Predefined top news sources per country.</p>
         * <p>Format: start with the word <code>top</code>, followed by the number of desired sources, and then the two-letter country code <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a>.</p>
         * <p>Multiple countries with the number of top sources can be specified as a comma-separated string.</p>
         */
        _FinalStage predefinedSources(Optional<String> predefinedSources);

        _FinalStage predefinedSources(String predefinedSources);

        /**
         * <p>One or more news sources to narrow down the search. The format must be a domain URL. Subdomains, such as <code>finance.yahoo.com</code>, are also acceptable.To specify multiple sources, use a comma-separated string.</p>
         */
        _FinalStage sources(Optional<String> sources);

        _FinalStage sources(String sources);

        /**
         * <p>The news sources to exclude from the search. To exclude multiple sources, use a comma-separated string.</p>
         */
        _FinalStage notSources(Optional<String> notSources);

        _FinalStage notSources(String notSources);

        /**
         * <p>The language(s) of the search. The only accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_639-1">ISO 639-1</a> code. To select multiple languages, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang">Enumerated parameters &gt; Language</a>.</p>
         */
        _FinalStage lang(Optional<String> lang);

        _FinalStage lang(String lang);

        /**
         * <p>The language(s) to exclude from the search. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_639-1">ISO 639-1</a> code. To exclude multiple languages, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang">Enumerated parameters &gt; Language</a>.</p>
         */
        _FinalStage notLang(Optional<String> notLang);

        _FinalStage notLang(String notLang);

        /**
         * <p>The countries where the news publisher is located. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a> code. To select multiple countries, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country">Enumerated parameters &gt; Country</a>.</p>
         */
        _FinalStage countries(Optional<String> countries);

        _FinalStage countries(String countries);

        /**
         * <p>The publisher location countries to exclude from the search. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a> code. To exclude multiple countries, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country">Enumerated parameters &gt; Country</a>.</p>
         */
        _FinalStage notCountries(Optional<String> notCountries);

        _FinalStage notCountries(String notCountries);

        _FinalStage from(Optional<From> from);

        _FinalStage from(From from);

        _FinalStage to(Optional<To> to);

        _FinalStage to(To to);

        _FinalStage publishedDatePrecision(Optional<String> publishedDatePrecision);

        _FinalStage publishedDatePrecision(String publishedDatePrecision);

        _FinalStage byParseDate(Optional<Boolean> byParseDate);

        _FinalStage byParseDate(Boolean byParseDate);

        _FinalStage sortBy(Optional<SortBy> sortBy);

        _FinalStage sortBy(SortBy sortBy);

        _FinalStage rankedOnly(Optional<Boolean> rankedOnly);

        _FinalStage rankedOnly(Boolean rankedOnly);

        _FinalStage fromRank(Optional<Integer> fromRank);

        _FinalStage fromRank(Integer fromRank);

        _FinalStage toRank(Optional<Integer> toRank);

        _FinalStage toRank(Integer toRank);

        _FinalStage isHeadline(Optional<Boolean> isHeadline);

        _FinalStage isHeadline(Boolean isHeadline);

        _FinalStage isOpinion(Optional<Boolean> isOpinion);

        _FinalStage isOpinion(Boolean isOpinion);

        _FinalStage isPaidContent(Optional<Boolean> isPaidContent);

        _FinalStage isPaidContent(Boolean isPaidContent);

        /**
         * <p>The categorical URL(s) to filter your search. To filter your search by multiple categorical URLs, use a comma-separated string.</p>
         */
        _FinalStage parentUrl(Optional<String> parentUrl);

        _FinalStage parentUrl(String parentUrl);

        /**
         * <p>The complete URL(s) mentioned in the article. For multiple URLs, use a comma-separated string.</p>
         * <p>For more details, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
         */
        _FinalStage allLinks(Optional<String> allLinks);

        _FinalStage allLinks(String allLinks);

        /**
         * <p>The domain(s) mentioned in the article. For multiple domains, use a comma-separated string.</p>
         * <p>For more details, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
         */
        _FinalStage allDomainLinks(Optional<String> allDomainLinks);

        _FinalStage allDomainLinks(String allDomainLinks);

        /**
         * <p>The text content of links mentioned in the article. Searches for links where the anchor text contains the specified terms. For multiple terms, use a comma-separated string.</p>
         * <p><strong>Note</strong>: When this parameter is used, the response includes the <code>all_links_data</code> field with detailed link information.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
         */
        _FinalStage allLinksText(Optional<String> allLinksText);

        _FinalStage allLinksText(String allLinksText);

        _FinalStage wordCountMin(Optional<Integer> wordCountMin);

        _FinalStage wordCountMin(Integer wordCountMin);

        _FinalStage wordCountMax(Optional<Integer> wordCountMax);

        _FinalStage wordCountMax(Integer wordCountMax);

        _FinalStage page(Optional<Integer> page);

        _FinalStage page(Integer page);

        _FinalStage pageSize(Optional<Integer> pageSize);

        _FinalStage pageSize(Integer pageSize);

        _FinalStage includeTranslationFields(Optional<Boolean> includeTranslationFields);

        _FinalStage includeTranslationFields(Boolean includeTranslationFields);

        _FinalStage includeNlpData(Optional<Boolean> includeNlpData);

        _FinalStage includeNlpData(Boolean includeNlpData);

        _FinalStage hasNlp(Optional<Boolean> hasNlp);

        _FinalStage hasNlp(Boolean hasNlp);

        _FinalStage theme(Optional<String> theme);

        _FinalStage theme(String theme);

        _FinalStage notTheme(Optional<String> notTheme);

        _FinalStage notTheme(String notTheme);

        _FinalStage nerName(Optional<String> nerName);

        _FinalStage nerName(String nerName);

        _FinalStage titleSentimentMin(Optional<Float> titleSentimentMin);

        _FinalStage titleSentimentMin(Float titleSentimentMin);

        _FinalStage titleSentimentMax(Optional<Float> titleSentimentMax);

        _FinalStage titleSentimentMax(Float titleSentimentMax);

        _FinalStage contentSentimentMin(Optional<Float> contentSentimentMin);

        _FinalStage contentSentimentMin(Float contentSentimentMin);

        _FinalStage contentSentimentMax(Optional<Float> contentSentimentMax);

        _FinalStage contentSentimentMax(Float contentSentimentMax);

        /**
         * <p>Filters articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags, use a comma-separated string of tag IDs.</p>
         * <p><strong>Note</strong>: The <code>iptc_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see <a href="https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html">IPTC Media Topic NewsCodes</a>.</p>
         */
        _FinalStage iptcTags(Optional<String> iptcTags);

        _FinalStage iptcTags(String iptcTags);

        /**
         * <p>Inverse of the <code>iptc_tags</code> parameter. Excludes articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags to exclude, use a comma-separated string of tag IDs.</p>
         * <p><strong>Note</strong>: The <code>not_iptc_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see <a href="https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html">IPTC Media Topic NewsCodes</a>.</p>
         */
        _FinalStage notIptcTags(Optional<String> notIptcTags);

        _FinalStage notIptcTags(String notIptcTags);

        /**
         * <p>Filters articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories, use a comma-separated string.</p>
         * <p><strong>Note</strong>: The <code>iab_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see the <a href="https://iabtechlab.com/standards/content-taxonomy/">IAB Content taxonomy</a>.</p>
         */
        _FinalStage iabTags(Optional<String> iabTags);

        _FinalStage iabTags(String iabTags);

        /**
         * <p>Inverse of the <code>iab_tags</code> parameter. Excludes articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories to exclude, use a comma-separated string.</p>
         * <p><strong>Note</strong>: The <code>not_iab_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see the <a href="https://iabtechlab.com/standards/content-taxonomy/">IAB Content taxonomy</a>.</p>
         */
        _FinalStage notIabTags(Optional<String> notIabTags);

        _FinalStage notIabTags(String notIabTags);

        /**
         * <p>Filters articles based on provided taxonomy that is tailored to your specific needs and is accessible only with your API key. To specify tags, use the following pattern:</p>
         * <ul>
         * <li><code>custom_tags.taxonomy=Tag1,Tag2</code>, where <code>taxonomy</code> is the taxonomy name and <code>Tag1,Tag2</code> is a comma-separated list of tag names.</li>
         * </ul>
         * <p>Example: <code>custom_tags.industry=&quot;Manufacturing,Logistics&quot;</code></p>
         * <p>To learn more, see the <a href="https://www.newscatcherapi.com/docs/news-api/guides-and-concepts/custom-tags">Custom tags</a>.</p>
         */
        _FinalStage customTags(Optional<String> customTags);

        _FinalStage customTags(String customTags);

        _FinalStage robotsCompliant(Optional<Boolean> robotsCompliant);

        _FinalStage robotsCompliant(Boolean robotsCompliant);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AuthorNameStage, _FinalStage {
        private String authorName;

        private Optional<Boolean> robotsCompliant = Optional.empty();

        private Optional<String> customTags = Optional.empty();

        private Optional<String> notIabTags = Optional.empty();

        private Optional<String> iabTags = Optional.empty();

        private Optional<String> notIptcTags = Optional.empty();

        private Optional<String> iptcTags = Optional.empty();

        private Optional<Float> contentSentimentMax = Optional.empty();

        private Optional<Float> contentSentimentMin = Optional.empty();

        private Optional<Float> titleSentimentMax = Optional.empty();

        private Optional<Float> titleSentimentMin = Optional.empty();

        private Optional<String> nerName = Optional.empty();

        private Optional<String> notTheme = Optional.empty();

        private Optional<String> theme = Optional.empty();

        private Optional<Boolean> hasNlp = Optional.empty();

        private Optional<Boolean> includeNlpData = Optional.empty();

        private Optional<Boolean> includeTranslationFields = Optional.empty();

        private Optional<Integer> pageSize = Optional.empty();

        private Optional<Integer> page = Optional.empty();

        private Optional<Integer> wordCountMax = Optional.empty();

        private Optional<Integer> wordCountMin = Optional.empty();

        private Optional<String> allLinksText = Optional.empty();

        private Optional<String> allDomainLinks = Optional.empty();

        private Optional<String> allLinks = Optional.empty();

        private Optional<String> parentUrl = Optional.empty();

        private Optional<Boolean> isPaidContent = Optional.empty();

        private Optional<Boolean> isOpinion = Optional.empty();

        private Optional<Boolean> isHeadline = Optional.empty();

        private Optional<Integer> toRank = Optional.empty();

        private Optional<Integer> fromRank = Optional.empty();

        private Optional<Boolean> rankedOnly = Optional.empty();

        private Optional<SortBy> sortBy = Optional.empty();

        private Optional<Boolean> byParseDate = Optional.empty();

        private Optional<String> publishedDatePrecision = Optional.empty();

        private Optional<To> to = Optional.empty();

        private Optional<From> from = Optional.empty();

        private Optional<String> notCountries = Optional.empty();

        private Optional<String> countries = Optional.empty();

        private Optional<String> notLang = Optional.empty();

        private Optional<String> lang = Optional.empty();

        private Optional<String> notSources = Optional.empty();

        private Optional<String> sources = Optional.empty();

        private Optional<String> predefinedSources = Optional.empty();

        private Optional<String> notAuthorName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GetAuthorsRequest other) {
            authorName(other.getAuthorName());
            notAuthorName(other.getNotAuthorName());
            predefinedSources(other.getPredefinedSources());
            sources(other.getSources());
            notSources(other.getNotSources());
            lang(other.getLang());
            notLang(other.getNotLang());
            countries(other.getCountries());
            notCountries(other.getNotCountries());
            from(other.getFrom());
            to(other.getTo());
            publishedDatePrecision(other.getPublishedDatePrecision());
            byParseDate(other.getByParseDate());
            sortBy(other.getSortBy());
            rankedOnly(other.getRankedOnly());
            fromRank(other.getFromRank());
            toRank(other.getToRank());
            isHeadline(other.getIsHeadline());
            isOpinion(other.getIsOpinion());
            isPaidContent(other.getIsPaidContent());
            parentUrl(other.getParentUrl());
            allLinks(other.getAllLinks());
            allDomainLinks(other.getAllDomainLinks());
            allLinksText(other.getAllLinksText());
            wordCountMin(other.getWordCountMin());
            wordCountMax(other.getWordCountMax());
            page(other.getPage());
            pageSize(other.getPageSize());
            includeTranslationFields(other.getIncludeTranslationFields());
            includeNlpData(other.getIncludeNlpData());
            hasNlp(other.getHasNlp());
            theme(other.getTheme());
            notTheme(other.getNotTheme());
            nerName(other.getNerName());
            titleSentimentMin(other.getTitleSentimentMin());
            titleSentimentMax(other.getTitleSentimentMax());
            contentSentimentMin(other.getContentSentimentMin());
            contentSentimentMax(other.getContentSentimentMax());
            iptcTags(other.getIptcTags());
            notIptcTags(other.getNotIptcTags());
            iabTags(other.getIabTags());
            notIabTags(other.getNotIabTags());
            customTags(other.getCustomTags());
            robotsCompliant(other.getRobotsCompliant());
            return this;
        }

        @java.lang.Override
        @JsonSetter("author_name")
        public _FinalStage authorName(@NotNull String authorName) {
            this.authorName = Objects.requireNonNull(authorName, "authorName must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage robotsCompliant(Boolean robotsCompliant) {
            this.robotsCompliant = Optional.ofNullable(robotsCompliant);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "robots_compliant", nulls = Nulls.SKIP)
        public _FinalStage robotsCompliant(Optional<Boolean> robotsCompliant) {
            this.robotsCompliant = robotsCompliant;
            return this;
        }

        /**
         * <p>Filters articles based on provided taxonomy that is tailored to your specific needs and is accessible only with your API key. To specify tags, use the following pattern:</p>
         * <ul>
         * <li><code>custom_tags.taxonomy=Tag1,Tag2</code>, where <code>taxonomy</code> is the taxonomy name and <code>Tag1,Tag2</code> is a comma-separated list of tag names.</li>
         * </ul>
         * <p>Example: <code>custom_tags.industry=&quot;Manufacturing,Logistics&quot;</code></p>
         * <p>To learn more, see the <a href="https://www.newscatcherapi.com/docs/news-api/guides-and-concepts/custom-tags">Custom tags</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage customTags(String customTags) {
            this.customTags = Optional.ofNullable(customTags);
            return this;
        }

        /**
         * <p>Filters articles based on provided taxonomy that is tailored to your specific needs and is accessible only with your API key. To specify tags, use the following pattern:</p>
         * <ul>
         * <li><code>custom_tags.taxonomy=Tag1,Tag2</code>, where <code>taxonomy</code> is the taxonomy name and <code>Tag1,Tag2</code> is a comma-separated list of tag names.</li>
         * </ul>
         * <p>Example: <code>custom_tags.industry=&quot;Manufacturing,Logistics&quot;</code></p>
         * <p>To learn more, see the <a href="https://www.newscatcherapi.com/docs/news-api/guides-and-concepts/custom-tags">Custom tags</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "custom_tags", nulls = Nulls.SKIP)
        public _FinalStage customTags(Optional<String> customTags) {
            this.customTags = customTags;
            return this;
        }

        /**
         * <p>Inverse of the <code>iab_tags</code> parameter. Excludes articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories to exclude, use a comma-separated string.</p>
         * <p><strong>Note</strong>: The <code>not_iab_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see the <a href="https://iabtechlab.com/standards/content-taxonomy/">IAB Content taxonomy</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage notIabTags(String notIabTags) {
            this.notIabTags = Optional.ofNullable(notIabTags);
            return this;
        }

        /**
         * <p>Inverse of the <code>iab_tags</code> parameter. Excludes articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories to exclude, use a comma-separated string.</p>
         * <p><strong>Note</strong>: The <code>not_iab_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see the <a href="https://iabtechlab.com/standards/content-taxonomy/">IAB Content taxonomy</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "not_iab_tags", nulls = Nulls.SKIP)
        public _FinalStage notIabTags(Optional<String> notIabTags) {
            this.notIabTags = notIabTags;
            return this;
        }

        /**
         * <p>Filters articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories, use a comma-separated string.</p>
         * <p><strong>Note</strong>: The <code>iab_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see the <a href="https://iabtechlab.com/standards/content-taxonomy/">IAB Content taxonomy</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iabTags(String iabTags) {
            this.iabTags = Optional.ofNullable(iabTags);
            return this;
        }

        /**
         * <p>Filters articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories, use a comma-separated string.</p>
         * <p><strong>Note</strong>: The <code>iab_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see the <a href="https://iabtechlab.com/standards/content-taxonomy/">IAB Content taxonomy</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "iab_tags", nulls = Nulls.SKIP)
        public _FinalStage iabTags(Optional<String> iabTags) {
            this.iabTags = iabTags;
            return this;
        }

        /**
         * <p>Inverse of the <code>iptc_tags</code> parameter. Excludes articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags to exclude, use a comma-separated string of tag IDs.</p>
         * <p><strong>Note</strong>: The <code>not_iptc_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see <a href="https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html">IPTC Media Topic NewsCodes</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage notIptcTags(String notIptcTags) {
            this.notIptcTags = Optional.ofNullable(notIptcTags);
            return this;
        }

        /**
         * <p>Inverse of the <code>iptc_tags</code> parameter. Excludes articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags to exclude, use a comma-separated string of tag IDs.</p>
         * <p><strong>Note</strong>: The <code>not_iptc_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see <a href="https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html">IPTC Media Topic NewsCodes</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "not_iptc_tags", nulls = Nulls.SKIP)
        public _FinalStage notIptcTags(Optional<String> notIptcTags) {
            this.notIptcTags = notIptcTags;
            return this;
        }

        /**
         * <p>Filters articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags, use a comma-separated string of tag IDs.</p>
         * <p><strong>Note</strong>: The <code>iptc_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see <a href="https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html">IPTC Media Topic NewsCodes</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iptcTags(String iptcTags) {
            this.iptcTags = Optional.ofNullable(iptcTags);
            return this;
        }

        /**
         * <p>Filters articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags, use a comma-separated string of tag IDs.</p>
         * <p><strong>Note</strong>: The <code>iptc_tags</code> parameter is only available in the <code>v3_nlp_iptc_tags</code> subscription plan.</p>
         * <p>To learn more, see <a href="https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html">IPTC Media Topic NewsCodes</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "iptc_tags", nulls = Nulls.SKIP)
        public _FinalStage iptcTags(Optional<String> iptcTags) {
            this.iptcTags = iptcTags;
            return this;
        }

        @java.lang.Override
        public _FinalStage contentSentimentMax(Float contentSentimentMax) {
            this.contentSentimentMax = Optional.ofNullable(contentSentimentMax);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "content_sentiment_max", nulls = Nulls.SKIP)
        public _FinalStage contentSentimentMax(Optional<Float> contentSentimentMax) {
            this.contentSentimentMax = contentSentimentMax;
            return this;
        }

        @java.lang.Override
        public _FinalStage contentSentimentMin(Float contentSentimentMin) {
            this.contentSentimentMin = Optional.ofNullable(contentSentimentMin);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "content_sentiment_min", nulls = Nulls.SKIP)
        public _FinalStage contentSentimentMin(Optional<Float> contentSentimentMin) {
            this.contentSentimentMin = contentSentimentMin;
            return this;
        }

        @java.lang.Override
        public _FinalStage titleSentimentMax(Float titleSentimentMax) {
            this.titleSentimentMax = Optional.ofNullable(titleSentimentMax);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "title_sentiment_max", nulls = Nulls.SKIP)
        public _FinalStage titleSentimentMax(Optional<Float> titleSentimentMax) {
            this.titleSentimentMax = titleSentimentMax;
            return this;
        }

        @java.lang.Override
        public _FinalStage titleSentimentMin(Float titleSentimentMin) {
            this.titleSentimentMin = Optional.ofNullable(titleSentimentMin);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "title_sentiment_min", nulls = Nulls.SKIP)
        public _FinalStage titleSentimentMin(Optional<Float> titleSentimentMin) {
            this.titleSentimentMin = titleSentimentMin;
            return this;
        }

        @java.lang.Override
        public _FinalStage nerName(String nerName) {
            this.nerName = Optional.ofNullable(nerName);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "ner_name", nulls = Nulls.SKIP)
        public _FinalStage nerName(Optional<String> nerName) {
            this.nerName = nerName;
            return this;
        }

        @java.lang.Override
        public _FinalStage notTheme(String notTheme) {
            this.notTheme = Optional.ofNullable(notTheme);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "not_theme", nulls = Nulls.SKIP)
        public _FinalStage notTheme(Optional<String> notTheme) {
            this.notTheme = notTheme;
            return this;
        }

        @java.lang.Override
        public _FinalStage theme(String theme) {
            this.theme = Optional.ofNullable(theme);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "theme", nulls = Nulls.SKIP)
        public _FinalStage theme(Optional<String> theme) {
            this.theme = theme;
            return this;
        }

        @java.lang.Override
        public _FinalStage hasNlp(Boolean hasNlp) {
            this.hasNlp = Optional.ofNullable(hasNlp);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "has_nlp", nulls = Nulls.SKIP)
        public _FinalStage hasNlp(Optional<Boolean> hasNlp) {
            this.hasNlp = hasNlp;
            return this;
        }

        @java.lang.Override
        public _FinalStage includeNlpData(Boolean includeNlpData) {
            this.includeNlpData = Optional.ofNullable(includeNlpData);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "include_nlp_data", nulls = Nulls.SKIP)
        public _FinalStage includeNlpData(Optional<Boolean> includeNlpData) {
            this.includeNlpData = includeNlpData;
            return this;
        }

        @java.lang.Override
        public _FinalStage includeTranslationFields(Boolean includeTranslationFields) {
            this.includeTranslationFields = Optional.ofNullable(includeTranslationFields);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "include_translation_fields", nulls = Nulls.SKIP)
        public _FinalStage includeTranslationFields(Optional<Boolean> includeTranslationFields) {
            this.includeTranslationFields = includeTranslationFields;
            return this;
        }

        @java.lang.Override
        public _FinalStage pageSize(Integer pageSize) {
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "page_size", nulls = Nulls.SKIP)
        public _FinalStage pageSize(Optional<Integer> pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        @java.lang.Override
        public _FinalStage page(Integer page) {
            this.page = Optional.ofNullable(page);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "page", nulls = Nulls.SKIP)
        public _FinalStage page(Optional<Integer> page) {
            this.page = page;
            return this;
        }

        @java.lang.Override
        public _FinalStage wordCountMax(Integer wordCountMax) {
            this.wordCountMax = Optional.ofNullable(wordCountMax);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "word_count_max", nulls = Nulls.SKIP)
        public _FinalStage wordCountMax(Optional<Integer> wordCountMax) {
            this.wordCountMax = wordCountMax;
            return this;
        }

        @java.lang.Override
        public _FinalStage wordCountMin(Integer wordCountMin) {
            this.wordCountMin = Optional.ofNullable(wordCountMin);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "word_count_min", nulls = Nulls.SKIP)
        public _FinalStage wordCountMin(Optional<Integer> wordCountMin) {
            this.wordCountMin = wordCountMin;
            return this;
        }

        /**
         * <p>The text content of links mentioned in the article. Searches for links where the anchor text contains the specified terms. For multiple terms, use a comma-separated string.</p>
         * <p><strong>Note</strong>: When this parameter is used, the response includes the <code>all_links_data</code> field with detailed link information.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage allLinksText(String allLinksText) {
            this.allLinksText = Optional.ofNullable(allLinksText);
            return this;
        }

        /**
         * <p>The text content of links mentioned in the article. Searches for links where the anchor text contains the specified terms. For multiple terms, use a comma-separated string.</p>
         * <p><strong>Note</strong>: When this parameter is used, the response includes the <code>all_links_data</code> field with detailed link information.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "all_links_text", nulls = Nulls.SKIP)
        public _FinalStage allLinksText(Optional<String> allLinksText) {
            this.allLinksText = allLinksText;
            return this;
        }

        /**
         * <p>The domain(s) mentioned in the article. For multiple domains, use a comma-separated string.</p>
         * <p>For more details, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage allDomainLinks(String allDomainLinks) {
            this.allDomainLinks = Optional.ofNullable(allDomainLinks);
            return this;
        }

        /**
         * <p>The domain(s) mentioned in the article. For multiple domains, use a comma-separated string.</p>
         * <p>For more details, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "all_domain_links", nulls = Nulls.SKIP)
        public _FinalStage allDomainLinks(Optional<String> allDomainLinks) {
            this.allDomainLinks = allDomainLinks;
            return this;
        }

        /**
         * <p>The complete URL(s) mentioned in the article. For multiple URLs, use a comma-separated string.</p>
         * <p>For more details, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage allLinks(String allLinks) {
            this.allLinks = Optional.ofNullable(allLinks);
            return this;
        }

        /**
         * <p>The complete URL(s) mentioned in the article. For multiple URLs, use a comma-separated string.</p>
         * <p>For more details, see <a href="https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url">Search by URL</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "all_links", nulls = Nulls.SKIP)
        public _FinalStage allLinks(Optional<String> allLinks) {
            this.allLinks = allLinks;
            return this;
        }

        /**
         * <p>The categorical URL(s) to filter your search. To filter your search by multiple categorical URLs, use a comma-separated string.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage parentUrl(String parentUrl) {
            this.parentUrl = Optional.ofNullable(parentUrl);
            return this;
        }

        /**
         * <p>The categorical URL(s) to filter your search. To filter your search by multiple categorical URLs, use a comma-separated string.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "parent_url", nulls = Nulls.SKIP)
        public _FinalStage parentUrl(Optional<String> parentUrl) {
            this.parentUrl = parentUrl;
            return this;
        }

        @java.lang.Override
        public _FinalStage isPaidContent(Boolean isPaidContent) {
            this.isPaidContent = Optional.ofNullable(isPaidContent);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "is_paid_content", nulls = Nulls.SKIP)
        public _FinalStage isPaidContent(Optional<Boolean> isPaidContent) {
            this.isPaidContent = isPaidContent;
            return this;
        }

        @java.lang.Override
        public _FinalStage isOpinion(Boolean isOpinion) {
            this.isOpinion = Optional.ofNullable(isOpinion);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "is_opinion", nulls = Nulls.SKIP)
        public _FinalStage isOpinion(Optional<Boolean> isOpinion) {
            this.isOpinion = isOpinion;
            return this;
        }

        @java.lang.Override
        public _FinalStage isHeadline(Boolean isHeadline) {
            this.isHeadline = Optional.ofNullable(isHeadline);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "is_headline", nulls = Nulls.SKIP)
        public _FinalStage isHeadline(Optional<Boolean> isHeadline) {
            this.isHeadline = isHeadline;
            return this;
        }

        @java.lang.Override
        public _FinalStage toRank(Integer toRank) {
            this.toRank = Optional.ofNullable(toRank);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "to_rank", nulls = Nulls.SKIP)
        public _FinalStage toRank(Optional<Integer> toRank) {
            this.toRank = toRank;
            return this;
        }

        @java.lang.Override
        public _FinalStage fromRank(Integer fromRank) {
            this.fromRank = Optional.ofNullable(fromRank);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "from_rank", nulls = Nulls.SKIP)
        public _FinalStage fromRank(Optional<Integer> fromRank) {
            this.fromRank = fromRank;
            return this;
        }

        @java.lang.Override
        public _FinalStage rankedOnly(Boolean rankedOnly) {
            this.rankedOnly = Optional.ofNullable(rankedOnly);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "ranked_only", nulls = Nulls.SKIP)
        public _FinalStage rankedOnly(Optional<Boolean> rankedOnly) {
            this.rankedOnly = rankedOnly;
            return this;
        }

        @java.lang.Override
        public _FinalStage sortBy(SortBy sortBy) {
            this.sortBy = Optional.ofNullable(sortBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "sort_by", nulls = Nulls.SKIP)
        public _FinalStage sortBy(Optional<SortBy> sortBy) {
            this.sortBy = sortBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage byParseDate(Boolean byParseDate) {
            this.byParseDate = Optional.ofNullable(byParseDate);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "by_parse_date", nulls = Nulls.SKIP)
        public _FinalStage byParseDate(Optional<Boolean> byParseDate) {
            this.byParseDate = byParseDate;
            return this;
        }

        @java.lang.Override
        public _FinalStage publishedDatePrecision(String publishedDatePrecision) {
            this.publishedDatePrecision = Optional.ofNullable(publishedDatePrecision);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "published_date_precision", nulls = Nulls.SKIP)
        public _FinalStage publishedDatePrecision(Optional<String> publishedDatePrecision) {
            this.publishedDatePrecision = publishedDatePrecision;
            return this;
        }

        @java.lang.Override
        public _FinalStage to(To to) {
            this.to = Optional.ofNullable(to);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "to_", nulls = Nulls.SKIP)
        public _FinalStage to(Optional<To> to) {
            this.to = to;
            return this;
        }

        @java.lang.Override
        public _FinalStage from(From from) {
            this.from = Optional.ofNullable(from);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "from_", nulls = Nulls.SKIP)
        public _FinalStage from(Optional<From> from) {
            this.from = from;
            return this;
        }

        /**
         * <p>The publisher location countries to exclude from the search. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a> code. To exclude multiple countries, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country">Enumerated parameters &gt; Country</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage notCountries(String notCountries) {
            this.notCountries = Optional.ofNullable(notCountries);
            return this;
        }

        /**
         * <p>The publisher location countries to exclude from the search. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a> code. To exclude multiple countries, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country">Enumerated parameters &gt; Country</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "not_countries", nulls = Nulls.SKIP)
        public _FinalStage notCountries(Optional<String> notCountries) {
            this.notCountries = notCountries;
            return this;
        }

        /**
         * <p>The countries where the news publisher is located. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a> code. To select multiple countries, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country">Enumerated parameters &gt; Country</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage countries(String countries) {
            this.countries = Optional.ofNullable(countries);
            return this;
        }

        /**
         * <p>The countries where the news publisher is located. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a> code. To select multiple countries, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country">Enumerated parameters &gt; Country</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "countries", nulls = Nulls.SKIP)
        public _FinalStage countries(Optional<String> countries) {
            this.countries = countries;
            return this;
        }

        /**
         * <p>The language(s) to exclude from the search. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_639-1">ISO 639-1</a> code. To exclude multiple languages, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang">Enumerated parameters &gt; Language</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage notLang(String notLang) {
            this.notLang = Optional.ofNullable(notLang);
            return this;
        }

        /**
         * <p>The language(s) to exclude from the search. The accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_639-1">ISO 639-1</a> code. To exclude multiple languages, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang">Enumerated parameters &gt; Language</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "not_lang", nulls = Nulls.SKIP)
        public _FinalStage notLang(Optional<String> notLang) {
            this.notLang = notLang;
            return this;
        }

        /**
         * <p>The language(s) of the search. The only accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_639-1">ISO 639-1</a> code. To select multiple languages, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang">Enumerated parameters &gt; Language</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage lang(String lang) {
            this.lang = Optional.ofNullable(lang);
            return this;
        }

        /**
         * <p>The language(s) of the search. The only accepted format is the two-letter <a href="https://en.wikipedia.org/wiki/ISO_639-1">ISO 639-1</a> code. To select multiple languages, use a comma-separated string.</p>
         * <p>To learn more, see <a href="https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang">Enumerated parameters &gt; Language</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "lang", nulls = Nulls.SKIP)
        public _FinalStage lang(Optional<String> lang) {
            this.lang = lang;
            return this;
        }

        /**
         * <p>The news sources to exclude from the search. To exclude multiple sources, use a comma-separated string.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage notSources(String notSources) {
            this.notSources = Optional.ofNullable(notSources);
            return this;
        }

        /**
         * <p>The news sources to exclude from the search. To exclude multiple sources, use a comma-separated string.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "not_sources", nulls = Nulls.SKIP)
        public _FinalStage notSources(Optional<String> notSources) {
            this.notSources = notSources;
            return this;
        }

        /**
         * <p>One or more news sources to narrow down the search. The format must be a domain URL. Subdomains, such as <code>finance.yahoo.com</code>, are also acceptable.To specify multiple sources, use a comma-separated string.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage sources(String sources) {
            this.sources = Optional.ofNullable(sources);
            return this;
        }

        /**
         * <p>One or more news sources to narrow down the search. The format must be a domain URL. Subdomains, such as <code>finance.yahoo.com</code>, are also acceptable.To specify multiple sources, use a comma-separated string.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "sources", nulls = Nulls.SKIP)
        public _FinalStage sources(Optional<String> sources) {
            this.sources = sources;
            return this;
        }

        /**
         * <p>Predefined top news sources per country.</p>
         * <p>Format: start with the word <code>top</code>, followed by the number of desired sources, and then the two-letter country code <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a>.</p>
         * <p>Multiple countries with the number of top sources can be specified as a comma-separated string.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage predefinedSources(String predefinedSources) {
            this.predefinedSources = Optional.ofNullable(predefinedSources);
            return this;
        }

        /**
         * <p>Predefined top news sources per country.</p>
         * <p>Format: start with the word <code>top</code>, followed by the number of desired sources, and then the two-letter country code <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a>.</p>
         * <p>Multiple countries with the number of top sources can be specified as a comma-separated string.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "predefined_sources", nulls = Nulls.SKIP)
        public _FinalStage predefinedSources(Optional<String> predefinedSources) {
            this.predefinedSources = predefinedSources;
            return this;
        }

        /**
         * <p>The list of author names to exclude from your search. To exclude articles by specific authors, use a comma-separated string.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage notAuthorName(String notAuthorName) {
            this.notAuthorName = Optional.ofNullable(notAuthorName);
            return this;
        }

        /**
         * <p>The list of author names to exclude from your search. To exclude articles by specific authors, use a comma-separated string.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "not_author_name", nulls = Nulls.SKIP)
        public _FinalStage notAuthorName(Optional<String> notAuthorName) {
            this.notAuthorName = notAuthorName;
            return this;
        }

        @java.lang.Override
        public GetAuthorsRequest build() {
            return new GetAuthorsRequest(
                    authorName,
                    notAuthorName,
                    predefinedSources,
                    sources,
                    notSources,
                    lang,
                    notLang,
                    countries,
                    notCountries,
                    from,
                    to,
                    publishedDatePrecision,
                    byParseDate,
                    sortBy,
                    rankedOnly,
                    fromRank,
                    toRank,
                    isHeadline,
                    isOpinion,
                    isPaidContent,
                    parentUrl,
                    allLinks,
                    allDomainLinks,
                    allLinksText,
                    wordCountMin,
                    wordCountMax,
                    page,
                    pageSize,
                    includeTranslationFields,
                    includeNlpData,
                    hasNlp,
                    theme,
                    notTheme,
                    nerName,
                    titleSentimentMin,
                    titleSentimentMax,
                    contentSentimentMin,
                    contentSentimentMax,
                    iptcTags,
                    notIptcTags,
                    iabTags,
                    notIabTags,
                    customTags,
                    robotsCompliant,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
