/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ClusteredSearchResponseDto.Builder.class)
public final class ClusteredSearchResponseDto implements IBaseSearchResponseDto, IClusteredArticlesDto {
    private final String status;

    private final int totalHits;

    private final int page;

    private final int totalPages;

    private final int pageSize;

    private final int clustersCount;

    private final List<ClusterEntity> clusters;

    private final Optional<Map<String, Object>> userInput;

    private final Map<String, Object> additionalProperties;

    private ClusteredSearchResponseDto(
            String status,
            int totalHits,
            int page,
            int totalPages,
            int pageSize,
            int clustersCount,
            List<ClusterEntity> clusters,
            Optional<Map<String, Object>> userInput,
            Map<String, Object> additionalProperties) {
        this.status = status;
        this.totalHits = totalHits;
        this.page = page;
        this.totalPages = totalPages;
        this.pageSize = pageSize;
        this.clustersCount = clustersCount;
        this.clusters = clusters;
        this.userInput = userInput;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The status of the response.
     */
    @JsonProperty("status")
    @java.lang.Override
    public String getStatus() {
        return status;
    }

    /**
     * @return The total number of articles matching the search criteria.
     */
    @JsonProperty("total_hits")
    @java.lang.Override
    public int getTotalHits() {
        return totalHits;
    }

    /**
     * @return The current page number of the results.
     */
    @JsonProperty("page")
    @java.lang.Override
    public int getPage() {
        return page;
    }

    /**
     * @return The total number of pages available for the given search criteria.
     */
    @JsonProperty("total_pages")
    @java.lang.Override
    public int getTotalPages() {
        return totalPages;
    }

    /**
     * @return The number of articles per page.
     */
    @JsonProperty("page_size")
    @java.lang.Override
    public int getPageSize() {
        return pageSize;
    }

    /**
     * @return The number of clusters in the search results.
     */
    @JsonProperty("clusters_count")
    @java.lang.Override
    public int getClustersCount() {
        return clustersCount;
    }

    /**
     * @return A list of clusters found in the search results.
     */
    @JsonProperty("clusters")
    @java.lang.Override
    public List<ClusterEntity> getClusters() {
        return clusters;
    }

    @JsonProperty("user_input")
    public Optional<Map<String, Object>> getUserInput() {
        return userInput;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClusteredSearchResponseDto && equalTo((ClusteredSearchResponseDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ClusteredSearchResponseDto other) {
        return status.equals(other.status)
                && totalHits == other.totalHits
                && page == other.page
                && totalPages == other.totalPages
                && pageSize == other.pageSize
                && clustersCount == other.clustersCount
                && clusters.equals(other.clusters)
                && userInput.equals(other.userInput);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.status,
                this.totalHits,
                this.page,
                this.totalPages,
                this.pageSize,
                this.clustersCount,
                this.clusters,
                this.userInput);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static StatusStage builder() {
        return new Builder();
    }

    public interface StatusStage {
        TotalHitsStage status(@NotNull String status);

        Builder from(ClusteredSearchResponseDto other);
    }

    public interface TotalHitsStage {
        PageStage totalHits(int totalHits);
    }

    public interface PageStage {
        TotalPagesStage page(int page);
    }

    public interface TotalPagesStage {
        PageSizeStage totalPages(int totalPages);
    }

    public interface PageSizeStage {
        ClustersCountStage pageSize(int pageSize);
    }

    public interface ClustersCountStage {
        _FinalStage clustersCount(int clustersCount);
    }

    public interface _FinalStage {
        ClusteredSearchResponseDto build();

        _FinalStage clusters(List<ClusterEntity> clusters);

        _FinalStage addClusters(ClusterEntity clusters);

        _FinalStage addAllClusters(List<ClusterEntity> clusters);

        _FinalStage userInput(Optional<Map<String, Object>> userInput);

        _FinalStage userInput(Map<String, Object> userInput);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements StatusStage,
                    TotalHitsStage,
                    PageStage,
                    TotalPagesStage,
                    PageSizeStage,
                    ClustersCountStage,
                    _FinalStage {
        private String status;

        private int totalHits;

        private int page;

        private int totalPages;

        private int pageSize;

        private int clustersCount;

        private Optional<Map<String, Object>> userInput = Optional.empty();

        private List<ClusterEntity> clusters = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ClusteredSearchResponseDto other) {
            status(other.getStatus());
            totalHits(other.getTotalHits());
            page(other.getPage());
            totalPages(other.getTotalPages());
            pageSize(other.getPageSize());
            clustersCount(other.getClustersCount());
            clusters(other.getClusters());
            userInput(other.getUserInput());
            return this;
        }

        /**
         * <p>The status of the response.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public TotalHitsStage status(@NotNull String status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>The total number of articles matching the search criteria.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("total_hits")
        public PageStage totalHits(int totalHits) {
            this.totalHits = totalHits;
            return this;
        }

        /**
         * <p>The current page number of the results.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("page")
        public TotalPagesStage page(int page) {
            this.page = page;
            return this;
        }

        /**
         * <p>The total number of pages available for the given search criteria.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("total_pages")
        public PageSizeStage totalPages(int totalPages) {
            this.totalPages = totalPages;
            return this;
        }

        /**
         * <p>The number of articles per page.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("page_size")
        public ClustersCountStage pageSize(int pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /**
         * <p>The number of clusters in the search results.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("clusters_count")
        public _FinalStage clustersCount(int clustersCount) {
            this.clustersCount = clustersCount;
            return this;
        }

        @java.lang.Override
        public _FinalStage userInput(Map<String, Object> userInput) {
            this.userInput = Optional.ofNullable(userInput);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "user_input", nulls = Nulls.SKIP)
        public _FinalStage userInput(Optional<Map<String, Object>> userInput) {
            this.userInput = userInput;
            return this;
        }

        /**
         * <p>A list of clusters found in the search results.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllClusters(List<ClusterEntity> clusters) {
            this.clusters.addAll(clusters);
            return this;
        }

        /**
         * <p>A list of clusters found in the search results.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addClusters(ClusterEntity clusters) {
            this.clusters.add(clusters);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "clusters", nulls = Nulls.SKIP)
        public _FinalStage clusters(List<ClusterEntity> clusters) {
            this.clusters.clear();
            this.clusters.addAll(clusters);
            return this;
        }

        @java.lang.Override
        public ClusteredSearchResponseDto build() {
            return new ClusteredSearchResponseDto(
                    status,
                    totalHits,
                    page,
                    totalPages,
                    pageSize,
                    clustersCount,
                    clusters,
                    userInput,
                    additionalProperties);
        }
    }
}
