/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Cluster.Builder.class)
public final class Cluster {
    private final String clusterId;

    private final int clusterSize;

    private final List<Map<String, Object>> articles;

    private final Map<String, Object> additionalProperties;

    private Cluster(
            String clusterId,
            int clusterSize,
            List<Map<String, Object>> articles,
            Map<String, Object> additionalProperties) {
        this.clusterId = clusterId;
        this.clusterSize = clusterSize;
        this.articles = articles;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("cluster_id")
    public String getClusterId() {
        return clusterId;
    }

    @JsonProperty("cluster_size")
    public int getClusterSize() {
        return clusterSize;
    }

    @JsonProperty("articles")
    public List<Map<String, Object>> getArticles() {
        return articles;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Cluster && equalTo((Cluster) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Cluster other) {
        return clusterId.equals(other.clusterId) && clusterSize == other.clusterSize && articles.equals(other.articles);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.clusterId, this.clusterSize, this.articles);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ClusterIdStage builder() {
        return new Builder();
    }

    public interface ClusterIdStage {
        ClusterSizeStage clusterId(@NotNull String clusterId);

        Builder from(Cluster other);
    }

    public interface ClusterSizeStage {
        _FinalStage clusterSize(int clusterSize);
    }

    public interface _FinalStage {
        Cluster build();

        _FinalStage articles(List<Map<String, Object>> articles);

        _FinalStage addArticles(Map<String, Object> articles);

        _FinalStage addAllArticles(List<Map<String, Object>> articles);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ClusterIdStage, ClusterSizeStage, _FinalStage {
        private String clusterId;

        private int clusterSize;

        private List<Map<String, Object>> articles = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Cluster other) {
            clusterId(other.getClusterId());
            clusterSize(other.getClusterSize());
            articles(other.getArticles());
            return this;
        }

        @java.lang.Override
        @JsonSetter("cluster_id")
        public ClusterSizeStage clusterId(@NotNull String clusterId) {
            this.clusterId = Objects.requireNonNull(clusterId, "clusterId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("cluster_size")
        public _FinalStage clusterSize(int clusterSize) {
            this.clusterSize = clusterSize;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllArticles(List<Map<String, Object>> articles) {
            this.articles.addAll(articles);
            return this;
        }

        @java.lang.Override
        public _FinalStage addArticles(Map<String, Object> articles) {
            this.articles.add(articles);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "articles", nulls = Nulls.SKIP)
        public _FinalStage articles(List<Map<String, Object>> articles) {
            this.articles.clear();
            this.articles.addAll(articles);
            return this;
        }

        @java.lang.Override
        public Cluster build() {
            return new Cluster(clusterId, clusterSize, articles, additionalProperties);
        }
    }
}
