/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FailedAuthorsResponseDto.Builder.class)
public final class FailedAuthorsResponseDto implements IBaseSearchResponseDto {
    private final String status;

    private final int totalHits;

    private final int page;

    private final int totalPages;

    private final int pageSize;

    private final Optional<List<Map<String, Object>>> articles;

    private final Optional<Map<String, Object>> userInput;

    private final Map<String, Object> additionalProperties;

    private FailedAuthorsResponseDto(
            String status,
            int totalHits,
            int page,
            int totalPages,
            int pageSize,
            Optional<List<Map<String, Object>>> articles,
            Optional<Map<String, Object>> userInput,
            Map<String, Object> additionalProperties) {
        this.status = status;
        this.totalHits = totalHits;
        this.page = page;
        this.totalPages = totalPages;
        this.pageSize = pageSize;
        this.articles = articles;
        this.userInput = userInput;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The status of the response.
     */
    @JsonProperty("status")
    @java.lang.Override
    public String getStatus() {
        return status;
    }

    /**
     * @return The total number of articles matching the search criteria.
     */
    @JsonProperty("total_hits")
    @java.lang.Override
    public int getTotalHits() {
        return totalHits;
    }

    /**
     * @return The current page number of the results.
     */
    @JsonProperty("page")
    @java.lang.Override
    public int getPage() {
        return page;
    }

    /**
     * @return The total number of pages available for the given search criteria.
     */
    @JsonProperty("total_pages")
    @java.lang.Override
    public int getTotalPages() {
        return totalPages;
    }

    /**
     * @return The number of articles per page.
     */
    @JsonProperty("page_size")
    @java.lang.Override
    public int getPageSize() {
        return pageSize;
    }

    /**
     * @return An empty list of articles, as no matches were found.
     */
    @JsonProperty("articles")
    public Optional<List<Map<String, Object>>> getArticles() {
        return articles;
    }

    @JsonProperty("user_input")
    public Optional<Map<String, Object>> getUserInput() {
        return userInput;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FailedAuthorsResponseDto && equalTo((FailedAuthorsResponseDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FailedAuthorsResponseDto other) {
        return status.equals(other.status)
                && totalHits == other.totalHits
                && page == other.page
                && totalPages == other.totalPages
                && pageSize == other.pageSize
                && articles.equals(other.articles)
                && userInput.equals(other.userInput);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.status, this.totalHits, this.page, this.totalPages, this.pageSize, this.articles, this.userInput);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static StatusStage builder() {
        return new Builder();
    }

    public interface StatusStage {
        TotalHitsStage status(@NotNull String status);

        Builder from(FailedAuthorsResponseDto other);
    }

    public interface TotalHitsStage {
        PageStage totalHits(int totalHits);
    }

    public interface PageStage {
        TotalPagesStage page(int page);
    }

    public interface TotalPagesStage {
        PageSizeStage totalPages(int totalPages);
    }

    public interface PageSizeStage {
        _FinalStage pageSize(int pageSize);
    }

    public interface _FinalStage {
        FailedAuthorsResponseDto build();

        _FinalStage articles(Optional<List<Map<String, Object>>> articles);

        _FinalStage articles(List<Map<String, Object>> articles);

        _FinalStage userInput(Optional<Map<String, Object>> userInput);

        _FinalStage userInput(Map<String, Object> userInput);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements StatusStage, TotalHitsStage, PageStage, TotalPagesStage, PageSizeStage, _FinalStage {
        private String status;

        private int totalHits;

        private int page;

        private int totalPages;

        private int pageSize;

        private Optional<Map<String, Object>> userInput = Optional.empty();

        private Optional<List<Map<String, Object>>> articles = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FailedAuthorsResponseDto other) {
            status(other.getStatus());
            totalHits(other.getTotalHits());
            page(other.getPage());
            totalPages(other.getTotalPages());
            pageSize(other.getPageSize());
            articles(other.getArticles());
            userInput(other.getUserInput());
            return this;
        }

        /**
         * <p>The status of the response.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public TotalHitsStage status(@NotNull String status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>The total number of articles matching the search criteria.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("total_hits")
        public PageStage totalHits(int totalHits) {
            this.totalHits = totalHits;
            return this;
        }

        /**
         * <p>The current page number of the results.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("page")
        public TotalPagesStage page(int page) {
            this.page = page;
            return this;
        }

        /**
         * <p>The total number of pages available for the given search criteria.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("total_pages")
        public PageSizeStage totalPages(int totalPages) {
            this.totalPages = totalPages;
            return this;
        }

        /**
         * <p>The number of articles per page.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("page_size")
        public _FinalStage pageSize(int pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        @java.lang.Override
        public _FinalStage userInput(Map<String, Object> userInput) {
            this.userInput = Optional.ofNullable(userInput);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "user_input", nulls = Nulls.SKIP)
        public _FinalStage userInput(Optional<Map<String, Object>> userInput) {
            this.userInput = userInput;
            return this;
        }

        /**
         * <p>An empty list of articles, as no matches were found.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage articles(List<Map<String, Object>> articles) {
            this.articles = Optional.ofNullable(articles);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "articles", nulls = Nulls.SKIP)
        public _FinalStage articles(Optional<List<Map<String, Object>>> articles) {
            this.articles = articles;
            return this;
        }

        @java.lang.Override
        public FailedAuthorsResponseDto build() {
            return new FailedAuthorsResponseDto(
                    status, totalHits, page, totalPages, pageSize, articles, userInput, additionalProperties);
        }
    }
}
