/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PublishedDatePrecision {
    public static final PublishedDatePrecision FULL = new PublishedDatePrecision(Value.FULL, "full");

    public static final PublishedDatePrecision DATE = new PublishedDatePrecision(Value.DATE, "date");

    public static final PublishedDatePrecision TIMEZONE_UNKNOWN =
            new PublishedDatePrecision(Value.TIMEZONE_UNKNOWN, "timezone unknown");

    private final Value value;

    private final String string;

    PublishedDatePrecision(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PublishedDatePrecision
                        && this.string.equals(((PublishedDatePrecision) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case FULL:
                return visitor.visitFull();
            case DATE:
                return visitor.visitDate();
            case TIMEZONE_UNKNOWN:
                return visitor.visitTimezoneUnknown();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PublishedDatePrecision valueOf(String value) {
        switch (value) {
            case "full":
                return FULL;
            case "date":
                return DATE;
            case "timezone unknown":
                return TIMEZONE_UNKNOWN;
            default:
                return new PublishedDatePrecision(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        FULL,

        TIMEZONE_UNKNOWN,

        DATE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitFull();

        T visitTimezoneUnknown();

        T visitDate();

        T visitUnknown(String unknownType);
    }
}
