/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SearchResponse.Builder.class)
public final class SearchResponse {
    private final Optional<String> status;

    private final int totalHits;

    private final int page;

    private final int totalPages;

    private final int pageSize;

    private final List<Map<String, Object>> articles;

    private final Map<String, Object> userInput;

    private final Map<String, Object> additionalProperties;

    private SearchResponse(
            Optional<String> status,
            int totalHits,
            int page,
            int totalPages,
            int pageSize,
            List<Map<String, Object>> articles,
            Map<String, Object> userInput,
            Map<String, Object> additionalProperties) {
        this.status = status;
        this.totalHits = totalHits;
        this.page = page;
        this.totalPages = totalPages;
        this.pageSize = pageSize;
        this.articles = articles;
        this.userInput = userInput;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("status")
    public Optional<String> getStatus() {
        return status;
    }

    @JsonProperty("total_hits")
    public int getTotalHits() {
        return totalHits;
    }

    @JsonProperty("page")
    public int getPage() {
        return page;
    }

    @JsonProperty("total_pages")
    public int getTotalPages() {
        return totalPages;
    }

    @JsonProperty("page_size")
    public int getPageSize() {
        return pageSize;
    }

    @JsonProperty("articles")
    public List<Map<String, Object>> getArticles() {
        return articles;
    }

    @JsonProperty("user_input")
    public Map<String, Object> getUserInput() {
        return userInput;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SearchResponse && equalTo((SearchResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SearchResponse other) {
        return status.equals(other.status)
                && totalHits == other.totalHits
                && page == other.page
                && totalPages == other.totalPages
                && pageSize == other.pageSize
                && articles.equals(other.articles)
                && userInput.equals(other.userInput);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.status, this.totalHits, this.page, this.totalPages, this.pageSize, this.articles, this.userInput);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TotalHitsStage builder() {
        return new Builder();
    }

    public interface TotalHitsStage {
        PageStage totalHits(int totalHits);

        Builder from(SearchResponse other);
    }

    public interface PageStage {
        TotalPagesStage page(int page);
    }

    public interface TotalPagesStage {
        PageSizeStage totalPages(int totalPages);
    }

    public interface PageSizeStage {
        _FinalStage pageSize(int pageSize);
    }

    public interface _FinalStage {
        SearchResponse build();

        _FinalStage status(Optional<String> status);

        _FinalStage status(String status);

        _FinalStage articles(List<Map<String, Object>> articles);

        _FinalStage addArticles(Map<String, Object> articles);

        _FinalStage addAllArticles(List<Map<String, Object>> articles);

        _FinalStage userInput(Map<String, Object> userInput);

        _FinalStage putAllUserInput(Map<String, Object> userInput);

        _FinalStage userInput(String key, Object value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements TotalHitsStage, PageStage, TotalPagesStage, PageSizeStage, _FinalStage {
        private int totalHits;

        private int page;

        private int totalPages;

        private int pageSize;

        private Map<String, Object> userInput = new LinkedHashMap<>();

        private List<Map<String, Object>> articles = new ArrayList<>();

        private Optional<String> status = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SearchResponse other) {
            status(other.getStatus());
            totalHits(other.getTotalHits());
            page(other.getPage());
            totalPages(other.getTotalPages());
            pageSize(other.getPageSize());
            articles(other.getArticles());
            userInput(other.getUserInput());
            return this;
        }

        @java.lang.Override
        @JsonSetter("total_hits")
        public PageStage totalHits(int totalHits) {
            this.totalHits = totalHits;
            return this;
        }

        @java.lang.Override
        @JsonSetter("page")
        public TotalPagesStage page(int page) {
            this.page = page;
            return this;
        }

        @java.lang.Override
        @JsonSetter("total_pages")
        public PageSizeStage totalPages(int totalPages) {
            this.totalPages = totalPages;
            return this;
        }

        @java.lang.Override
        @JsonSetter("page_size")
        public _FinalStage pageSize(int pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        @java.lang.Override
        public _FinalStage userInput(String key, Object value) {
            this.userInput.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllUserInput(Map<String, Object> userInput) {
            this.userInput.putAll(userInput);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "user_input", nulls = Nulls.SKIP)
        public _FinalStage userInput(Map<String, Object> userInput) {
            this.userInput.clear();
            this.userInput.putAll(userInput);
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllArticles(List<Map<String, Object>> articles) {
            this.articles.addAll(articles);
            return this;
        }

        @java.lang.Override
        public _FinalStage addArticles(Map<String, Object> articles) {
            this.articles.add(articles);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "articles", nulls = Nulls.SKIP)
        public _FinalStage articles(List<Map<String, Object>> articles) {
            this.articles.clear();
            this.articles.addAll(articles);
            return this;
        }

        @java.lang.Override
        public _FinalStage status(String status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public _FinalStage status(Optional<String> status) {
            this.status = status;
            return this;
        }

        @java.lang.Override
        public SearchResponse build() {
            return new SearchResponse(
                    status, totalHits, page, totalPages, pageSize, articles, userInput, additionalProperties);
        }
    }
}
