/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SimilarDocument.Builder.class)
public final class SimilarDocument {
    private final String id;

    private final double score;

    private final String title;

    private final String link;

    private final Map<String, Object> additionalProperties;

    private SimilarDocument(
            String id, double score, String title, String link, Map<String, Object> additionalProperties) {
        this.id = id;
        this.score = score;
        this.title = title;
        this.link = link;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier of the similar document.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The relevance score of the similar document.
     */
    @JsonProperty("score")
    public double getScore() {
        return score;
    }

    /**
     * @return The title of the similar document.
     */
    @JsonProperty("title")
    public String getTitle() {
        return title;
    }

    /**
     * @return The link to the similar document.
     */
    @JsonProperty("link")
    public String getLink() {
        return link;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SimilarDocument && equalTo((SimilarDocument) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SimilarDocument other) {
        return id.equals(other.id) && score == other.score && title.equals(other.title) && link.equals(other.link);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.score, this.title, this.link);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        ScoreStage id(@NotNull String id);

        Builder from(SimilarDocument other);
    }

    public interface ScoreStage {
        TitleStage score(double score);
    }

    public interface TitleStage {
        LinkStage title(@NotNull String title);
    }

    public interface LinkStage {
        _FinalStage link(@NotNull String link);
    }

    public interface _FinalStage {
        SimilarDocument build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, ScoreStage, TitleStage, LinkStage, _FinalStage {
        private String id;

        private double score;

        private String title;

        private String link;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SimilarDocument other) {
            id(other.getId());
            score(other.getScore());
            title(other.getTitle());
            link(other.getLink());
            return this;
        }

        /**
         * <p>The unique identifier of the similar document.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public ScoreStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The relevance score of the similar document.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("score")
        public TitleStage score(double score) {
            this.score = score;
            return this;
        }

        /**
         * <p>The title of the similar document.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("title")
        public LinkStage title(@NotNull String title) {
            this.title = Objects.requireNonNull(title, "title must not be null");
            return this;
        }

        /**
         * <p>The link to the similar document.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("link")
        public _FinalStage link(@NotNull String link) {
            this.link = Objects.requireNonNull(link, "link must not be null");
            return this;
        }

        @java.lang.Override
        public SimilarDocument build() {
            return new SimilarDocument(id, score, title, link, additionalProperties);
        }
    }
}
