/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.searchsimilar.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.newscatcher.api.core.ObjectMappers;
import com.newscatcher.api.types.FailedSearchSimilarResponseDto;
import com.newscatcher.api.types.SearchSimilarResponseDto;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = SearchSimilarGetResponse.Deserializer.class)
public final class SearchSimilarGetResponse {
    private final Object value;

    private final int type;

    private SearchSimilarGetResponse(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((SearchSimilarResponseDto) this.value);
        } else if (this.type == 1) {
            return visitor.visit((FailedSearchSimilarResponseDto) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SearchSimilarGetResponse && equalTo((SearchSimilarGetResponse) other);
    }

    private boolean equalTo(SearchSimilarGetResponse other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static SearchSimilarGetResponse of(SearchSimilarResponseDto value) {
        return new SearchSimilarGetResponse(value, 0);
    }

    public static SearchSimilarGetResponse of(FailedSearchSimilarResponseDto value) {
        return new SearchSimilarGetResponse(value, 1);
    }

    public interface Visitor<T> {
        T visit(SearchSimilarResponseDto value);

        T visit(FailedSearchSimilarResponseDto value);
    }

    static final class Deserializer extends StdDeserializer<SearchSimilarGetResponse> {
        Deserializer() {
            super(SearchSimilarGetResponse.class);
        }

        @java.lang.Override
        public SearchSimilarGetResponse deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, SearchSimilarResponseDto.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, FailedSearchSimilarResponseDto.class));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
