/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.breakingnews;

import com.newscatcher.api.core.ClientOptions;
import com.newscatcher.api.core.RequestOptions;
import com.newscatcher.api.resources.breakingnews.requests.GetBreakingNewsRequest;
import com.newscatcher.api.resources.breakingnews.requests.PostBreakingNewsRequest;
import com.newscatcher.api.types.BreakingNewsResponseDto;
import java.util.concurrent.CompletableFuture;

public class AsyncBreakingNewsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawBreakingNewsClient rawClient;

    public AsyncBreakingNewsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawBreakingNewsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawBreakingNewsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieves breaking news articles and sorts them based on specified criteria.
     */
    public CompletableFuture<BreakingNewsResponseDto> get() {
        return this.rawClient.get().thenApply(response -> response.body());
    }

    /**
     * Retrieves breaking news articles and sorts them based on specified criteria.
     */
    public CompletableFuture<BreakingNewsResponseDto> get(RequestOptions requestOptions) {
        return this.rawClient.get(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves breaking news articles and sorts them based on specified criteria.
     */
    public CompletableFuture<BreakingNewsResponseDto> get(GetBreakingNewsRequest request) {
        return this.rawClient.get(request).thenApply(response -> response.body());
    }

    /**
     * Retrieves breaking news articles and sorts them based on specified criteria.
     */
    public CompletableFuture<BreakingNewsResponseDto> get(
            GetBreakingNewsRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves breaking news articles and sorts them based on specified criteria.
     */
    public CompletableFuture<BreakingNewsResponseDto> post() {
        return this.rawClient.post().thenApply(response -> response.body());
    }

    /**
     * Retrieves breaking news articles and sorts them based on specified criteria.
     */
    public CompletableFuture<BreakingNewsResponseDto> post(RequestOptions requestOptions) {
        return this.rawClient.post(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves breaking news articles and sorts them based on specified criteria.
     */
    public CompletableFuture<BreakingNewsResponseDto> post(PostBreakingNewsRequest request) {
        return this.rawClient.post(request).thenApply(response -> response.body());
    }

    /**
     * Retrieves breaking news articles and sorts them based on specified criteria.
     */
    public CompletableFuture<BreakingNewsResponseDto> post(
            PostBreakingNewsRequest request, RequestOptions requestOptions) {
        return this.rawClient.post(request, requestOptions).thenApply(response -> response.body());
    }
}
