/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.search.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SearchGetRequestPublishedDatePrecision {
    FULL("full"),

    TIMEZONE_UNKNOWN("timezone unknown"),

    DATE("date");

    private final String value;

    SearchGetRequestPublishedDatePrecision(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
