/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.search.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SearchGetRequestSortBy {
    RELEVANCY("relevancy"),

    DATE("date"),

    RANK("rank");

    private final String value;

    SearchGetRequestSortBy(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
