/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.searchbylink;

import com.newscatcher.api.core.ClientOptions;
import com.newscatcher.api.core.RequestOptions;
import com.newscatcher.api.resources.searchbylink.requests.SearchByLinkGetRequest;
import com.newscatcher.api.resources.searchbylink.requests.SearchByLinkPostRequest;
import com.newscatcher.api.types.SearchResponseDto;
import java.util.concurrent.CompletableFuture;

public class AsyncSearchByLinkClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawSearchByLinkClient rawClient;

    public AsyncSearchByLinkClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawSearchByLinkClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawSearchByLinkClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public CompletableFuture<SearchResponseDto> searchByLinkGet() {
        return this.rawClient.searchByLinkGet().thenApply(response -> response.body());
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public CompletableFuture<SearchResponseDto> searchByLinkGet(RequestOptions requestOptions) {
        return this.rawClient.searchByLinkGet(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public CompletableFuture<SearchResponseDto> searchByLinkGet(SearchByLinkGetRequest request) {
        return this.rawClient.searchByLinkGet(request).thenApply(response -> response.body());
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public CompletableFuture<SearchResponseDto> searchByLinkGet(
            SearchByLinkGetRequest request, RequestOptions requestOptions) {
        return this.rawClient.searchByLinkGet(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public CompletableFuture<SearchResponseDto> searchByLinkPost() {
        return this.rawClient.searchByLinkPost().thenApply(response -> response.body());
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public CompletableFuture<SearchResponseDto> searchByLinkPost(RequestOptions requestOptions) {
        return this.rawClient.searchByLinkPost(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public CompletableFuture<SearchResponseDto> searchByLinkPost(SearchByLinkPostRequest request) {
        return this.rawClient.searchByLinkPost(request).thenApply(response -> response.body());
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public CompletableFuture<SearchResponseDto> searchByLinkPost(
            SearchByLinkPostRequest request, RequestOptions requestOptions) {
        return this.rawClient.searchByLinkPost(request, requestOptions).thenApply(response -> response.body());
    }
}
