/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.searchbylink;

import com.newscatcher.api.core.ClientOptions;
import com.newscatcher.api.core.RequestOptions;
import com.newscatcher.api.resources.searchbylink.requests.GetSearchByLinkRequest;
import com.newscatcher.api.resources.searchbylink.requests.PostSearchByLinkRequest;
import com.newscatcher.api.types.SearchResponseDto;
import java.util.concurrent.CompletableFuture;

public class AsyncSearchByLinkClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawSearchByLinkClient rawClient;

    public AsyncSearchByLinkClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawSearchByLinkClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawSearchByLinkClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public CompletableFuture<SearchResponseDto> get() {
        return this.rawClient.get().thenApply(response -> response.body());
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public CompletableFuture<SearchResponseDto> get(RequestOptions requestOptions) {
        return this.rawClient.get(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public CompletableFuture<SearchResponseDto> get(GetSearchByLinkRequest request) {
        return this.rawClient.get(request).thenApply(response -> response.body());
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public CompletableFuture<SearchResponseDto> get(GetSearchByLinkRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public CompletableFuture<SearchResponseDto> post() {
        return this.rawClient.post().thenApply(response -> response.body());
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public CompletableFuture<SearchResponseDto> post(RequestOptions requestOptions) {
        return this.rawClient.post(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public CompletableFuture<SearchResponseDto> post(PostSearchByLinkRequest request) {
        return this.rawClient.post(request).thenApply(response -> response.body());
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public CompletableFuture<SearchResponseDto> post(PostSearchByLinkRequest request, RequestOptions requestOptions) {
        return this.rawClient.post(request, requestOptions).thenApply(response -> response.body());
    }
}
