/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.searchbylink;

import com.newscatcher.api.core.ClientOptions;
import com.newscatcher.api.core.RequestOptions;
import com.newscatcher.api.resources.searchbylink.requests.GetSearchByLinkRequest;
import com.newscatcher.api.resources.searchbylink.requests.PostSearchByLinkRequest;
import com.newscatcher.api.types.SearchResponseDto;

public class SearchByLinkClient {
    protected final ClientOptions clientOptions;

    private final RawSearchByLinkClient rawClient;

    public SearchByLinkClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSearchByLinkClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSearchByLinkClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public SearchResponseDto get() {
        return this.rawClient.get().body();
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public SearchResponseDto get(RequestOptions requestOptions) {
        return this.rawClient.get(requestOptions).body();
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public SearchResponseDto get(GetSearchByLinkRequest request) {
        return this.rawClient.get(request).body();
    }

    /**
     * Searches for articles based on specified links or IDs. You can filter results by date range.
     */
    public SearchResponseDto get(GetSearchByLinkRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).body();
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public SearchResponseDto post() {
        return this.rawClient.post().body();
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public SearchResponseDto post(RequestOptions requestOptions) {
        return this.rawClient.post(requestOptions).body();
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public SearchResponseDto post(PostSearchByLinkRequest request) {
        return this.rawClient.post(request).body();
    }

    /**
     * Searches for articles using their ID(s) or link(s).
     */
    public SearchResponseDto post(PostSearchByLinkRequest request, RequestOptions requestOptions) {
        return this.rawClient.post(request, requestOptions).body();
    }
}
