/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api;

import static org.junit.jupiter.api.Assertions.*;

import com.newscatcher.api.core.ObjectMappers;
import com.newscatcher.api.resources.aggregationcount.types.GetAggregationCountResponse;
import com.newscatcher.api.resources.aggregationcount.types.PostAggregationCountResponse;
import com.newscatcher.api.resources.authors.types.GetAuthorsResponse;
import com.newscatcher.api.resources.authors.types.PostAuthorsResponse;
import com.newscatcher.api.resources.latestheadlines.types.GetLatestHeadlinesResponse;
import com.newscatcher.api.resources.latestheadlines.types.PostLatestHeadlinesResponse;
import com.newscatcher.api.resources.search.types.GetSearchResponse;
import com.newscatcher.api.resources.search.types.PostSearchResponse;
import com.newscatcher.api.types.AggregationCountResponseDto;
import com.newscatcher.api.types.SearchResponseDto;
import org.junit.jupiter.api.Test;

public final class UndiscriminatedUnionTest {
    @Test
    public void testGetSearchResponse_SearchResponseDto() throws Exception {
        String json = "{\"status\":\"test\",\"total_hits\":1,\"page\":1,\"total_pages\":1,\"page_size\":1}";
        GetSearchResponse union = ObjectMappers.JSON_MAPPER.readValue(json, GetSearchResponse.class);
        assertTrue(union.get() instanceof SearchResponseDto, "Expected SearchResponseDto but got different variant");
    }

    @Test
    public void testPostSearchResponse_SearchResponseDto() throws Exception {
        String json = "{\"status\":\"test\",\"total_hits\":1,\"page\":1,\"total_pages\":1,\"page_size\":1}";
        PostSearchResponse union = ObjectMappers.JSON_MAPPER.readValue(json, PostSearchResponse.class);
        assertTrue(union.get() instanceof SearchResponseDto, "Expected SearchResponseDto but got different variant");
    }

    @Test
    public void testGetLatestHeadlinesResponse_SearchResponseDto() throws Exception {
        String json = "{\"status\":\"test\",\"total_hits\":1,\"page\":1,\"total_pages\":1,\"page_size\":1}";
        GetLatestHeadlinesResponse union = ObjectMappers.JSON_MAPPER.readValue(json, GetLatestHeadlinesResponse.class);
        assertTrue(union.get() instanceof SearchResponseDto, "Expected SearchResponseDto but got different variant");
    }

    @Test
    public void testPostLatestHeadlinesResponse_SearchResponseDto() throws Exception {
        String json = "{\"status\":\"test\",\"total_hits\":1,\"page\":1,\"total_pages\":1,\"page_size\":1}";
        PostLatestHeadlinesResponse union =
                ObjectMappers.JSON_MAPPER.readValue(json, PostLatestHeadlinesResponse.class);
        assertTrue(union.get() instanceof SearchResponseDto, "Expected SearchResponseDto but got different variant");
    }

    @Test
    public void testGetAuthorsResponse_SearchResponseDto() throws Exception {
        String json = "{\"status\":\"test\",\"total_hits\":1,\"page\":1,\"total_pages\":1,\"page_size\":1}";
        GetAuthorsResponse union = ObjectMappers.JSON_MAPPER.readValue(json, GetAuthorsResponse.class);
        assertTrue(union.get() instanceof SearchResponseDto, "Expected SearchResponseDto but got different variant");
    }

    @Test
    public void testPostAuthorsResponse_SearchResponseDto() throws Exception {
        String json = "{\"status\":\"test\",\"total_hits\":1,\"page\":1,\"total_pages\":1,\"page_size\":1}";
        PostAuthorsResponse union = ObjectMappers.JSON_MAPPER.readValue(json, PostAuthorsResponse.class);
        assertTrue(union.get() instanceof SearchResponseDto, "Expected SearchResponseDto but got different variant");
    }

    @Test
    public void testGetAggregationCountResponse_AggregationCountResponseDto() throws Exception {
        String json = "{\"status\":\"test\",\"total_hits\":1,\"page\":1,\"total_pages\":1,\"page_size\":1}";
        GetAggregationCountResponse union =
                ObjectMappers.JSON_MAPPER.readValue(json, GetAggregationCountResponse.class);
        assertTrue(
                union.get() instanceof AggregationCountResponseDto,
                "Expected AggregationCountResponseDto but got different variant");
    }

    @Test
    public void testPostAggregationCountResponse_AggregationCountResponseDto() throws Exception {
        String json = "{\"status\":\"test\",\"total_hits\":1,\"page\":1,\"total_pages\":1,\"page_size\":1}";
        PostAggregationCountResponse union =
                ObjectMappers.JSON_MAPPER.readValue(json, PostAggregationCountResponse.class);
        assertTrue(
                union.get() instanceof AggregationCountResponseDto,
                "Expected AggregationCountResponseDto but got different variant");
    }
}
