/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.sources.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SourcesRequest.Builder.class)
public final class SourcesRequest {
    private final Optional<Object> lang;

    private final Optional<Object> countries;

    private final Optional<Object> predefinedSources;

    private final Optional<Boolean> includeAdditionalInfo;

    private final Optional<Integer> fromRank;

    private final Optional<Integer> toRank;

    private final Optional<Object> sourceName;

    private final Optional<Object> sourceUrl;

    private final Optional<Boolean> isNewsDomain;

    private final Optional<Object> newsDomainType;

    private final Optional<Object> newsType;

    private final Map<String, Object> additionalProperties;

    private SourcesRequest(
            Optional<Object> lang,
            Optional<Object> countries,
            Optional<Object> predefinedSources,
            Optional<Boolean> includeAdditionalInfo,
            Optional<Integer> fromRank,
            Optional<Integer> toRank,
            Optional<Object> sourceName,
            Optional<Object> sourceUrl,
            Optional<Boolean> isNewsDomain,
            Optional<Object> newsDomainType,
            Optional<Object> newsType,
            Map<String, Object> additionalProperties) {
        this.lang = lang;
        this.countries = countries;
        this.predefinedSources = predefinedSources;
        this.includeAdditionalInfo = includeAdditionalInfo;
        this.fromRank = fromRank;
        this.toRank = toRank;
        this.sourceName = sourceName;
        this.sourceUrl = sourceUrl;
        this.isNewsDomain = isNewsDomain;
        this.newsDomainType = newsDomainType;
        this.newsType = newsType;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("lang")
    public Optional<Object> getLang() {
        return lang;
    }

    @JsonProperty("countries")
    public Optional<Object> getCountries() {
        return countries;
    }

    @JsonProperty("predefined_sources")
    public Optional<Object> getPredefinedSources() {
        return predefinedSources;
    }

    @JsonProperty("include_additional_info")
    public Optional<Boolean> getIncludeAdditionalInfo() {
        return includeAdditionalInfo;
    }

    @JsonProperty("from_rank")
    public Optional<Integer> getFromRank() {
        return fromRank;
    }

    @JsonProperty("to_rank")
    public Optional<Integer> getToRank() {
        return toRank;
    }

    @JsonProperty("source_name")
    public Optional<Object> getSourceName() {
        return sourceName;
    }

    @JsonProperty("source_url")
    public Optional<Object> getSourceUrl() {
        return sourceUrl;
    }

    @JsonProperty("is_news_domain")
    public Optional<Boolean> getIsNewsDomain() {
        return isNewsDomain;
    }

    @JsonProperty("news_domain_type")
    public Optional<Object> getNewsDomainType() {
        return newsDomainType;
    }

    @JsonProperty("news_type")
    public Optional<Object> getNewsType() {
        return newsType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SourcesRequest && equalTo((SourcesRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SourcesRequest other) {
        return lang.equals(other.lang)
                && countries.equals(other.countries)
                && predefinedSources.equals(other.predefinedSources)
                && includeAdditionalInfo.equals(other.includeAdditionalInfo)
                && fromRank.equals(other.fromRank)
                && toRank.equals(other.toRank)
                && sourceName.equals(other.sourceName)
                && sourceUrl.equals(other.sourceUrl)
                && isNewsDomain.equals(other.isNewsDomain)
                && newsDomainType.equals(other.newsDomainType)
                && newsType.equals(other.newsType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.lang,
                this.countries,
                this.predefinedSources,
                this.includeAdditionalInfo,
                this.fromRank,
                this.toRank,
                this.sourceName,
                this.sourceUrl,
                this.isNewsDomain,
                this.newsDomainType,
                this.newsType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Object> lang = Optional.empty();

        private Optional<Object> countries = Optional.empty();

        private Optional<Object> predefinedSources = Optional.empty();

        private Optional<Boolean> includeAdditionalInfo = Optional.empty();

        private Optional<Integer> fromRank = Optional.empty();

        private Optional<Integer> toRank = Optional.empty();

        private Optional<Object> sourceName = Optional.empty();

        private Optional<Object> sourceUrl = Optional.empty();

        private Optional<Boolean> isNewsDomain = Optional.empty();

        private Optional<Object> newsDomainType = Optional.empty();

        private Optional<Object> newsType = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SourcesRequest other) {
            lang(other.getLang());
            countries(other.getCountries());
            predefinedSources(other.getPredefinedSources());
            includeAdditionalInfo(other.getIncludeAdditionalInfo());
            fromRank(other.getFromRank());
            toRank(other.getToRank());
            sourceName(other.getSourceName());
            sourceUrl(other.getSourceUrl());
            isNewsDomain(other.getIsNewsDomain());
            newsDomainType(other.getNewsDomainType());
            newsType(other.getNewsType());
            return this;
        }

        @JsonSetter(value = "lang", nulls = Nulls.SKIP)
        public Builder lang(Optional<Object> lang) {
            this.lang = lang;
            return this;
        }

        public Builder lang(Object lang) {
            this.lang = Optional.ofNullable(lang);
            return this;
        }

        @JsonSetter(value = "countries", nulls = Nulls.SKIP)
        public Builder countries(Optional<Object> countries) {
            this.countries = countries;
            return this;
        }

        public Builder countries(Object countries) {
            this.countries = Optional.ofNullable(countries);
            return this;
        }

        @JsonSetter(value = "predefined_sources", nulls = Nulls.SKIP)
        public Builder predefinedSources(Optional<Object> predefinedSources) {
            this.predefinedSources = predefinedSources;
            return this;
        }

        public Builder predefinedSources(Object predefinedSources) {
            this.predefinedSources = Optional.ofNullable(predefinedSources);
            return this;
        }

        @JsonSetter(value = "include_additional_info", nulls = Nulls.SKIP)
        public Builder includeAdditionalInfo(Optional<Boolean> includeAdditionalInfo) {
            this.includeAdditionalInfo = includeAdditionalInfo;
            return this;
        }

        public Builder includeAdditionalInfo(Boolean includeAdditionalInfo) {
            this.includeAdditionalInfo = Optional.ofNullable(includeAdditionalInfo);
            return this;
        }

        @JsonSetter(value = "from_rank", nulls = Nulls.SKIP)
        public Builder fromRank(Optional<Integer> fromRank) {
            this.fromRank = fromRank;
            return this;
        }

        public Builder fromRank(Integer fromRank) {
            this.fromRank = Optional.ofNullable(fromRank);
            return this;
        }

        @JsonSetter(value = "to_rank", nulls = Nulls.SKIP)
        public Builder toRank(Optional<Integer> toRank) {
            this.toRank = toRank;
            return this;
        }

        public Builder toRank(Integer toRank) {
            this.toRank = Optional.ofNullable(toRank);
            return this;
        }

        @JsonSetter(value = "source_name", nulls = Nulls.SKIP)
        public Builder sourceName(Optional<Object> sourceName) {
            this.sourceName = sourceName;
            return this;
        }

        public Builder sourceName(Object sourceName) {
            this.sourceName = Optional.ofNullable(sourceName);
            return this;
        }

        @JsonSetter(value = "source_url", nulls = Nulls.SKIP)
        public Builder sourceUrl(Optional<Object> sourceUrl) {
            this.sourceUrl = sourceUrl;
            return this;
        }

        public Builder sourceUrl(Object sourceUrl) {
            this.sourceUrl = Optional.ofNullable(sourceUrl);
            return this;
        }

        @JsonSetter(value = "is_news_domain", nulls = Nulls.SKIP)
        public Builder isNewsDomain(Optional<Boolean> isNewsDomain) {
            this.isNewsDomain = isNewsDomain;
            return this;
        }

        public Builder isNewsDomain(Boolean isNewsDomain) {
            this.isNewsDomain = Optional.ofNullable(isNewsDomain);
            return this;
        }

        @JsonSetter(value = "news_domain_type", nulls = Nulls.SKIP)
        public Builder newsDomainType(Optional<Object> newsDomainType) {
            this.newsDomainType = newsDomainType;
            return this;
        }

        public Builder newsDomainType(Object newsDomainType) {
            this.newsDomainType = Optional.ofNullable(newsDomainType);
            return this;
        }

        @JsonSetter(value = "news_type", nulls = Nulls.SKIP)
        public Builder newsType(Optional<Object> newsType) {
            this.newsType = newsType;
            return this;
        }

        public Builder newsType(Object newsType) {
            this.newsType = Optional.ofNullable(newsType);
            return this;
        }

        public SourcesRequest build() {
            return new SourcesRequest(
                    lang,
                    countries,
                    predefinedSources,
                    includeAdditionalInfo,
                    fromRank,
                    toRank,
                    sourceName,
                    sourceUrl,
                    isNewsDomain,
                    newsDomainType,
                    newsType,
                    additionalProperties);
        }
    }
}
