/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api;

import com.newscatcher.api.core.ClientOptions;
import com.newscatcher.api.core.Suppliers;
import com.newscatcher.api.resources.aggregation.AggregationClient;
import com.newscatcher.api.resources.authors.AuthorsClient;
import com.newscatcher.api.resources.breakingnews.BreakingNewsClient;
import com.newscatcher.api.resources.latestheadlines.LatestHeadlinesClient;
import com.newscatcher.api.resources.search.SearchClient;
import com.newscatcher.api.resources.searchbylink.SearchByLinkClient;
import com.newscatcher.api.resources.sources.SourcesClient;
import com.newscatcher.api.resources.subscription.SubscriptionClient;
import java.util.function.Supplier;

public class NewscatcherApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<SearchClient> searchClient;

    protected final Supplier<LatestHeadlinesClient> latestHeadlinesClient;

    protected final Supplier<BreakingNewsClient> breakingNewsClient;

    protected final Supplier<AuthorsClient> authorsClient;

    protected final Supplier<SearchByLinkClient> searchByLinkClient;

    protected final Supplier<SourcesClient> sourcesClient;

    protected final Supplier<AggregationClient> aggregationClient;

    protected final Supplier<SubscriptionClient> subscriptionClient;

    public NewscatcherApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.searchClient = Suppliers.memoize(() -> new SearchClient(clientOptions));
        this.latestHeadlinesClient = Suppliers.memoize(() -> new LatestHeadlinesClient(clientOptions));
        this.breakingNewsClient = Suppliers.memoize(() -> new BreakingNewsClient(clientOptions));
        this.authorsClient = Suppliers.memoize(() -> new AuthorsClient(clientOptions));
        this.searchByLinkClient = Suppliers.memoize(() -> new SearchByLinkClient(clientOptions));
        this.sourcesClient = Suppliers.memoize(() -> new SourcesClient(clientOptions));
        this.aggregationClient = Suppliers.memoize(() -> new AggregationClient(clientOptions));
        this.subscriptionClient = Suppliers.memoize(() -> new SubscriptionClient(clientOptions));
    }

    public SearchClient search() {
        return this.searchClient.get();
    }

    public LatestHeadlinesClient latestHeadlines() {
        return this.latestHeadlinesClient.get();
    }

    public BreakingNewsClient breakingNews() {
        return this.breakingNewsClient.get();
    }

    public AuthorsClient authors() {
        return this.authorsClient.get();
    }

    public SearchByLinkClient searchByLink() {
        return this.searchByLinkClient.get();
    }

    public SourcesClient sources() {
        return this.sourcesClient.get();
    }

    public AggregationClient aggregation() {
        return this.aggregationClient.get();
    }

    public SubscriptionClient subscription() {
        return this.subscriptionClient.get();
    }

    public static NewscatcherApiClientBuilder builder() {
        return new NewscatcherApiClientBuilder();
    }
}
