/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.api.resources.aggregationcount;

import com.newscatcher.api.core.ClientOptions;
import com.newscatcher.api.core.RequestOptions;
import com.newscatcher.api.resources.aggregationcount.requests.GetAggregationCountRequest;
import com.newscatcher.api.resources.aggregationcount.requests.PostAggregationCountRequest;
import com.newscatcher.api.resources.aggregationcount.types.GetAggregationCountResponse;
import com.newscatcher.api.resources.aggregationcount.types.PostAggregationCountResponse;

public class AggregationCountClient {
    protected final ClientOptions clientOptions;

    private final RawAggregationCountClient rawClient;

    public AggregationCountClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAggregationCountClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAggregationCountClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieves the count of articles aggregated by day or hour based on various search criteria, such as keyword, language, country, and source.
     */
    public GetAggregationCountResponse get(GetAggregationCountRequest request) {
        return this.rawClient.get(request).body();
    }

    /**
     * Retrieves the count of articles aggregated by day or hour based on various search criteria, such as keyword, language, country, and source.
     */
    public GetAggregationCountResponse get(GetAggregationCountRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).body();
    }

    /**
     * Retrieves the count of articles aggregated by day or hour based on various search criteria, such as keyword, language, country, and source.
     */
    public PostAggregationCountResponse post(PostAggregationCountRequest request) {
        return this.rawClient.post(request).body();
    }

    /**
     * Retrieves the count of articles aggregated by day or hour based on various search criteria, such as keyword, language, country, and source.
     */
    public PostAggregationCountResponse post(PostAggregationCountRequest request, RequestOptions requestOptions) {
        return this.rawClient.post(request, requestOptions).body();
    }
}
